### ISSUE TITLE
Additional settings like Picture Preset changes

### ISSUE THREAD

**Issue by helgek** [merdok/homebridge-webos-tv#371] opened 2021-05-04 10:10 UTC
Hi,

I finally found solution to change e.g. picture presets. Please see my last comment at:

https://community.home-assistant.io/t/lg-webos-change-picture-setting-mode-with-scripts/262915

Maybe something that could also be integrated into your solution?

Thanks and regards
Helge

**Comment by merdok** [comment] 2021-05-04 12:31
This looks like a very good info. It seems that it works over the websocket endpoint but not the same as all other commands. 

I will do some investigation and when I succeed then I will definitely include this in my plugin!

**Comment by helgek** [comment] 2021-05-04 14:51
Thank you for looking into this! I'm not a professional developer and unfortunately not very familiar with Python, but from what I was able to read all the additional commands available seem to be applied over websocket as well and no hacking seems to be involved (the commands executed seem to be in line with webos sdk information I could find on this (using luna commands, for which you need SSH access to the device which I couldn't obtain). 
I was so glad to see this working with my OLED55E97LA last night. And like you said there are even more commands in the code. Looks like this could be a game changer on how we can now also integrate these devices into automation workflows.

**Comment by merdok** [comment] 2021-05-04 16:16
@helgek do you know if that way it is possible to actually change the tv picture mode? Let's say i want to switch from game to expert.

**Comment by helgek** [comment] 2021-05-04 17:00
@merdok that is what I actually wanted to test tonight. Last night it was too late and I was just happy that I could adjust the parameters. I will test it later today and will let you know about the outcome.

**Comment by merdok** [comment] 2021-05-04 18:26
Okay. Please let me know if it is also possible to change the picture mode.

**Comment by helgek** [comment] 2021-05-04 19:26
Good news. The`client.start_calibration(picMode="game") ` makes the TV switch to the picture mode set in 'picMode'.
When I use other picMode for the following commands `client.set_oled_light` and so on it doesn't adjust values in these picture presets but in the picMode set in `client.start_calibration`. It seems to ignore the picMode in the commands following the start_calibration command.

**Comment by helgek** [comment] 2021-05-04 19:36
fyi - websocket command for get picture settings just got implemented here:
https://github.com/klattimer/LGWebOSRemote/pull/79/commits

**Comment by merdok** [comment] 2021-05-04 19:40
Yeah, i also got it working on my tv. Indeed starting the calibration switches to that picture mode which is good. 

Yes, i already had the picture settings implemented in my controller since the big update to version 2.0 so quite some time ago ;) I just did not have a use for that.

Anyway the issue is that at least i am not aware of any list of the available picture modes. I just did some try and error and found out that "game" and "cinema" works, but i have no idea what the other are called... do you have any info on that?

**Comment by helgek** [comment] 2021-05-04 19:43
yeah, just getting the settings values doesn't help much...
I was just about to paste the info which I just found on pictureModes :)) this is what I found:
https://www.webosose.org/docs/reference/ls2-api/com-webos-service-settings/#dimension

pictureMode | Optional | String | You can use the following values:vivid, normal, eco, cinema, game, sports, expert1, expert2

**Comment by KeyofBlueS** [comment] 2021-05-04 19:46
Hi,
from aiopylgtv readme:
`Known supported picMode strings are: SDR: cinema, expert1, expert2, game, technicolorExpert HDR10(+HLG): hdr_technicolorExpert, hdr_cinema, hdr_game DV: dolby_cinema_dark, dolby_cinema_bright, dolby_game`

Anyway, I can't get it to work:
```
$ python3 picture_settings.py
Traceback (most recent call last):
  File "/home/keyofblues/src/aiopylgtv/picture_settings.py", line 17, in <module>
    asyncio.run(runloop())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/keyofblues/src/aiopylgtv/picture_settings.py", line 8, in runloop
    await client.start_calibration(picMode="game")
  File "/usr/local/lib/python3.9/dist-packages/aiopylgtv/webos_client.py", line 1157, in start_calibration
    return await self.calibration_request(cal.CAL_START, picMode, data)
  File "/usr/local/lib/python3.9/dist-packages/aiopylgtv/webos_client.py", line 1153, in calibration_request
    return await self.request(ep.CALIBRATION, payload)
  File "/usr/local/lib/python3.9/dist-packages/aiopylgtv/webos_client.py", line 688, in request
    raise PyLGTVCmdError(error)
aiopylgtv.webos_client.PyLGTVCmdError: 500 Application error
```
Maybe my tv It's not compatible with calibration

**Comment by merdok** [comment] 2021-05-04 19:50
Yeah, it does not seems to work with all modes. For me only this work: `cinema, expert1, expert2, game`, so this is pretty limiting... but yeah it is possible to change the picture settings in that modes and that worked great for me :) If it just would work for all modes then this would be perfect, but right now this just seems like a 50/50 solution...

@KeyofBlueS what TV do you have?

**Comment by KeyofBlueS** [comment] 2021-05-04 19:54
It's a LG UN73003LC

**Comment by merdok** [comment] 2021-05-04 19:57
It is a webOS 5.0 TV so i think it should support it.

**Comment by helgek** [comment] 2021-05-04 19:59
for me also cinema, expert1, expert2, game, technicolorExpert work in HDMI Source without something plugged in.

dolby_cinema_dark, dolby_cinema_bright, dolby_game work with HDMI with FireTV plugged in.

**Comment by helgek** [comment] 2021-05-04 20:21
not sure if this helps. It looks like it could indicate that you can read the currently selected pictureMode: https://github.com/webosose/avoutputd/blob/32fa2fc02e76be75b0943a13e8c97d43fb71abdb/src/settings/picturesettings.cpp

also found tint, color and sharpness as additional values but in aiopylgtv only `client.set_color(picMode="game", value=40) ` works for me

**Comment by helgek** [comment] 2021-05-04 20:28
https://github.com/webosose/avoutputd/blob/32fa2fc02e76be75b0943a13e8c97d43fb71abdb/src/settings/picturemode.cpp

**Comment by merdok** [comment] 2021-05-04 20:29
That what you posted is a private api not accessible through the websocket endpoint.

**Comment by helgek** [comment] 2021-05-04 20:31
oh I see. Thanks for the explanation!

**Comment by helgek** [comment] 2021-05-04 20:41
Could this work to read the current pictureMode preset?

https://www.webosose.org/docs/reference/ls2-api/com-webos-service-settings/#getsystemsettingfactoryvalue

**Comment by helgek** [comment] 2021-05-04 20:53
Some interesting follow-up on picture presets:

https://github.com/home-assistant/home-assistant.io/issues/17685#issuecomment-832236791

**Comment by merdok** [comment] 2021-05-04 20:57
This is all unfortunately internal methods which are not available in the public websocket api. The public websocket endpoints internally call those methods but the results are filtered and exposed back with a limited scope. 

It is possibly to modify those websocket endpoints on your tv to give full access to the internal methods, but for that you need to get root access on your TV which is not a public knowledge and only a handful of people can do that at this point.

**Comment by helgek** [comment] 2021-05-04 21:07
I see. That's a pity. But I don't want to complain. For my purposes I'm more than happy with what I can do now with the calibration mode trick. All I initially wanted was to be able to automatically set the oled light setting depending on the light environment in the room and this can now be accomplished.

**Comment by merdok** [comment] 2021-05-04 21:14
Unfortunately just for a limited range of modes...

Also if you want to play around with calling internal endpoints, you can use my LgTvController which has a `lunaSend` function  which actually is a proxy for calling the internal methods. This actually works for some stuff like enabling the screen saver, but i could not get the picture settings to work and i am not sure why since the error messages are not propagated up when using the proxy call.

Here is an example: https://github.com/merdok/homebridge-webos-tv/blob/master/lib/LgTvController.js#L1323-L1333
If that would work then it would be possible to change the settings of any picture mode :)

**Comment by helgek** [comment] 2021-05-04 21:24
Yes, I already discovered these code lines with your remark :) Possibly this is restricted with intention although you mention scenarios where this command can be used. Yes, it's a pity that LG is not helping more with providing api transparency.

**Comment by luigi-lauro** [comment] 2021-05-09 07:52
Would be fantastic for automation if it would be possible to find a solution for this :-)

**Comment by helgek** [comment] 2021-05-10 13:17
@luigi-lauro  You can already use aiopylgtv to apply picture settings if you e.g. use Home Assistant, Open HAB, FHEM, etc. You just need to include the command line command in your home automation solution scripts. I'm not so familiar with Homebridge but it should be possible too, for instance with such a plugin https://github.com/hallos/homebridge-cmdtrigger . But I don't know if you can then also easily map it to a button in HomeKit.

**Comment by kongomongo** [comment] 2021-05-14 09:41
> Unfortunately just for a limited range of modes...
> 
> Also if you want to play around with calling internal endpoints, you can use my LgTvController which has a `lunaSend` function which actually is a proxy for calling the internal methods. This actually works for some stuff like enabling the screen saver, but i could not get the picture settings to work and i am not sure why since the error messages are not propagated up when using the proxy call.
> 
> Here is an example: https://github.com/merdok/homebridge-webos-tv/blob/master/lib/LgTvController.js#L1323-L1333
> If that would work then it would be possible to change the settings of any picture mode :)

Does getSystemSettings work for you at all via web iface? Getting permission problem.

```
send_command("status_", "subscribe", "ssap://settings/getSystemSettings", {"category": "picture", "keys": ["contrast", "backlight", "brightness", "color"]}, function(success, response){
          if (success) {
              debugLog(RESULT_OK, response);
          } else {
              debugLog(RESULT_ERROR, response);
          }
   });
lgtv.js:81 ---> Sending command:{"id":"status_54","type":"subscribe","uri":"ssap://settings/getSystemSettings"}
lgtv.js:63 <--- received: {"type":"error","id":"status_54","error":"401 insufficient permissions","payload":{}}
lgtv.js:707 true {type: "error", id: "status_54", error: "401 insufficient permissions", payload: {…}}

```

**Comment by merdok** [comment] 2021-05-14 10:11
Yes, it works! You need to make sure that all permissions are enabled!

**Comment by kongomongo** [comment] 2021-05-14 11:39
within the TV?

**Comment by merdok** [comment] 2021-05-14 12:10
No, in whatever tool you use to send the command, if you use my LgTvController then it already has all the necessary permissions enabled.

**Comment by kongomongo** [comment] 2021-05-14 12:41
OK thank you it works, but how do you get it to output the current picture mode? Can only seem to grab the settings subkey?

**Comment by merdok** [comment] 2021-05-14 15:23
It will not output the the picture mode since this is filtered out for the public web service. The settings is unfortunately the best you can get...

**Comment by kongomongo** [comment] 2021-05-14 18:25
ok then I guess theres no hope to set it, if even getting fails?

I saw some discussion above about internal/non-public api/interface. How can one access those?

**Comment by merdok** [comment] 2021-05-14 20:16
As a app developer you can access some of the internal functionality in an app, but in order to access everything you need to jailbreak your tv and gain root access.

**Comment by bendavid** [comment] 2021-05-22 03:28
@merdok building on your implementation here, and scraping some strings from the unpacked tv firmware, I worked out how to set picture mode and settings.

See the implementation in aiopylgtv here:
https://github.com/bendavid/aiopylgtv/blob/0.4.1/aiopylgtv/webos_client.py#L1162-L1437

The settings and picture modes can be set explicitly for specific inputs, modes, hdr modes, etc if desired, which should actually makes it feasible to use for robust automations.

I improved a bit on your lunaSend implementation by using closeAlert rather than a button press.

I couldn't find any way to get the returned data from the luna calls, any ideas?

**Comment by merdok** [comment] 2021-05-22 08:27
@bendavid nice! Great work! So i was just sending the request to the wrong service and that is why my attempts fail, damn...
Also you are right, closing the alert may be safer then sending the the ENTER key 👍 

As far as i know we will not be able to get the returned data from that workaround. Only the main service can return data and none of the public available services pass the returned data from those luna service calls to the main service. Although it is possible to modify one of the public services or write a custom one, but for that you need to jailbreak your tv which is not really a solution for everyone.

**Comment by merdok** [comment] 2021-05-22 13:05
@bendavid did you also maybe found out other possible categories and available settings for them? I guess there should also be categories like `sound, general or network` and a list of possible settings for them would be good.

**Comment by samy570** [comment] 2021-05-27 18:24
Someone know how Google assistant change the picture mode using à Hi Lg like command?

**Comment by luigi-lauro** [comment] 2021-05-28 19:49
Now that it's possible to set picture modes, it would be fantastic to be able to change pictureModes with an input spinner, which would be updated based on the content type (e.g. when in HDR filter available picture modes shown in input spinner should be only HDR picture modes, when in SDR or DolbyVision the same). This would make a terrific UI to be able to check & change picture mode by HomeKit :-)

**Comment by luigi-lauro** [comment] 2021-06-18 10:12
> Now that it's possible to set picture modes, it would be fantastic to be able to change pictureModes with an input spinner, which would be updated based on the content type (e.g. when in HDR filter available picture modes shown in input spinner should be only HDR picture modes, when in SDR or DolbyVision the same). This would make a terrific UI to be able to check & change picture mode by HomeKit :-)

Any comment on this proposal? :-)

**Comment by merdok** [comment] 2021-06-18 11:22
It is not possible to add another input spinner just for picture modes. Also I do not want to mix inputs with pictures modes as this is just confusing. 
A button for each picture mode will be the best that is doable with the limited UI in the Home app...

**Closed** 2021-09-29 21:19 UTC
