### ISSUE TITLE
Issues adding TV to HomeKit

### ISSUE THREAD

**Issue by JustJasper** [merdok/homebridge-webos-tv#336] opened 2020-12-31 14:24 UTC
Able to set up and add to HomeBridge (showing up in Accessories tab in HomeBridge, and works as expected there).

When adding to HomeKit, I go through: 

Add Accessory > I Don’t Have a Code or Cannot Scan > Select the TV > Enter HomeKit Code 

Then I just get ‘Connecting to TV’ for a long time but no progress.

I’ve tried deleting accessories/cachedAccessories, restarting the TV and Pi multiple times but with no luck.  Any suggestions?

**Comment by merdok** [comment] 2020-12-31 14:37
Did you enter the correct ip and mac address of your TV? Can your Raspberry Pi reach the TV in the network? Did you accept the connection on the TV when starting up homebridge?

**Comment by JustJasper** [comment] 2020-12-31 15:24
Yep, IP and MAC addresses are correct.  I can control the TV from the HomeBridge GUI (TV on/off, volume etc) all fine.  So the connection between the Pi and the TV must be fine, and yes, I accepted the connection when starting up HomeBridge.

**Comment by merdok** [comment] 2020-12-31 15:49
Ok, then this seems like some issue with your Home app, if you can control the app with the homebridge GUI then the plugin works fine! Maybe reset your home in homekit or try to clear the homebridge cache?

**Comment by JustJasper** [comment] 2020-12-31 16:13
Thanks, will continue to tinker and see what works.

**Comment by Veldkornet** [comment] 2021-01-05 14:16
I have the exact same issue FYI. 
Other devices from my HomeBride show up in HomeKit, just not the TV. 

I can see the TV from the HomeBridge UX abd can control it from there...

**Comment by merdok** [comment] 2021-01-05 15:40
@Veldkornet this definitely some kind of cache issue. Try to clear the homebridge cache or add it to a new home in HomeKit.

**Comment by Veldkornet** [comment] 2021-01-05 17:03
Did both, still nothing 😔

**Comment by merdok** [comment] 2021-01-05 17:58
Then you are not following the process described in the README or there is some kind of other issue with your homebridge setup. The plugin itself is working correctly.

**Comment by Veldkornet** [comment] 2021-01-05 18:46
Ha, you are correct ;) I was expecting it to just appear like my other plugins, completely forgot that I need to add it manually.
Apologies for hijacking the issue ;)

**Comment by infvmm** [comment] 2021-01-07 20:17
I have the same issue, i don´t know if @JustJasper could solve it. In my case i can control and link the tv on Alexa, i can control the tv from homebridge, following all the steps in the README, in the 5th step: "Enter the Homebridge PIN, this can be found under the QR code in Homebridge UI or your Homebridge logs, alternatively you can select Use Camera and scan the QR code again." 

Keep on connecting to the tv for a while and at the end fails, can´t reach the element. 

I activated the log on the homebridge and the plugin but no info is logged when it´s trying to link HomeKit with HomeBridge. I tried what you suggested, new home, clear cache, ....

I don´t know if the issue could be due to some version update of node, ... Any port closed by the firewall... 

I have connected other devices from Homebridge to HomeKit, all of them work with Alexa. 

I don´t know what I can try more :(

Version of Node.js v14.15.4
Version of npm v6.14.10
Version of homebridge 1.2.5

Thanks for helping just in advance.

**Comment by merdok** [comment] 2021-01-07 21:39
@infvmm are you sure that you enter the correct Home pin? The pin which you need to enter will appear in the debug log of homebridge when it is starting.

**Comment by infvmm** [comment] 2021-01-07 22:16
Yes thanks, i have used the correct Home pin all the times. But reading again the log I saw this entry: 

TV is running on port 35481.
Please add [TV] manually in Home app. Setup Code: .....

In this case what i did was disable the firewall of the server, then I added the TV on HomeKit, it worked perfect and very fast, then I activate the firewall of the server again and now it works perfectly, it seems it works even with the port closed, it could be it´s only needed to connect, i´ll try and in other case i will add the port to the firewall exceptions.

@JustJasper checki if you have the same issue with the firewall and the port, it could be your problem as mine. Now the plugin works perfect. 

Thanks @merdok for support.

**Comment by infvmm** [comment] 2021-01-07 22:31
It seems the port is random on the homebridge reboot, so after reboot it changed and it doesn´t work due to firewall again, how can i configure the port of the TV in a static way?.

**Comment by merdok** [comment] 2021-01-07 22:37
@infvmm you can configure the port in the config.json under `"bridge"`

**Comment by infvmm** [comment] 2021-01-08 22:42
Yes, but is not this port. As I have checked, the TV is starting each homebridge reboot in a different port with the message "XXXX is running on port YYYYY". The name of the tv is static and always the same, is taken from the name of the device and added a 4 letter code, but always the same. But the port it seems is initialized in a random way, because each time I reboot the homebridge, the port is different. The port of the bridge you mentioned is always the same and is static and as you say configured on config.json under "bridge". 

The problem is I don´t know where I can configure the other port and how to create it in a static way.

**Comment by rhyssmith** [comment] 2021-01-09 21:30
Just had exactly the same issue, and exactly the same solution worked nicely for me - specify the port range for homebridge to use, and open that port range via `firewall-cmd`. So thanks!

**Comment by merdok** [comment] 2021-01-09 21:33
@rhyssmith thanks for letting us know! It seems like quite some people have this issue so maybe i consider adding this to the README

**Comment by JustJasper** [comment] 2021-01-09 21:59
@infvmm @merdok Yep, this was the issue at my end too - all working fine now.  Thanks so much for troubleshooting!

For anyone reading with a similar issue, my confit ended up as follows:

```
...
"bridge": {
        "name": "Homebridge",
        "username": "0E:94:8E:57:36:7A",
        "pin": "176-67-900",
        "port": 51283
    },
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
    },
...
```

**Comment by merdok** [comment] 2021-01-10 08:07
Perfect! Thanks for the info!

**Closed by merdok** 2021-01-10 08:07 UTC

**Comment by vordenken** [comment] 2021-01-15 21:02
I'm here because I have the same problem. Adding the ports to the config doesn't work. At first I thought its because I run Homebridge in docker but even when I install it on my Mac without docker its just not working. 
I use Homebridge with other stuff successfully so I don't know what's the problem. Controlling the tv through the Homebridge web interface works as well. Any ideas?

**Comment by merdok** [comment] 2021-01-15 23:02
@vordenken you can check this issue and see if that fixes it for you https://github.com/merdok/homebridge-webos-tv/issues/340

**Comment by vordenken** [comment] 2021-01-16 14:21
Thanks for your reply @merdok . Unfortunately this does not fix my problem. 
Because I am running Homebridge in docker without Avahi, I thought maybe my setup is the problem but I just spun up the official Homebridge raspbian image and tested it: same problem.

**Comment by merdok** [comment] 2021-01-16 15:10
Then in your case I suspect a network issue. You probably have some firewall issues or your docket container has no access to the same network as your tv.

**Comment by vordenken** [comment] 2021-01-16 15:20
I don't have a firewall and its the same problem without docker and the official Homebridge version. Also I can use the Homebridge hue add-on without a problem so it kinda is related to this plugin? Does it work differently than the hue one? 
I'm out of ideas...

**Comment by merdok** [comment] 2021-01-16 15:34
With the firewall this i just a wild guess, it can be anything in your local environment
TV devices are external HomeKit accessories so they work slightly different then other plugins.

**Comment by olivere** [comment] 2021-01-16 16:08
I had the same connection problem: I just couldn't get past the PIN verification. For me it was due to the firewall.

I have Homebridge installed on a RaspberryPi. First thing I did was to configure a fixed range of ports (I used 52000-52999). Next, I opened that port range on the Pi with `sudo ufw allow 52000:52999/tcp`. That solved the connection problem. Everything's working fine now.

Thanks for this plugin!

**Comment by vordenken** [comment] 2021-01-16 16:36
Ok so I think I found the problem. First of all, this is completely my fault. Instead of trying to add the TV to the Home-app like you describe it in the readme, I only ever scanned the qr-code from homebridge-config-ui.
If I go with the "I Don't Have a Code or Cannot Scan" Button it shows the TV and I can control everything like a charm.

Because there are apparently quite a lot of people here with the issue, maybe you should make this more obvious in the readme.

Thanks for your help & thanks for this awesome plugin! Cheers

**Comment by merdok** [comment] 2021-01-16 16:55
Good to hear it is fixed! The first thing which i usually do in that kind of issues is point to the README ;)
