### ISSUE TITLE
Issue with power on

### ISSUE THREAD

**Issue by tomhoplon** [merdok/homebridge-webos-tv#129] opened 2019-03-07 08:59 UTC
Since upgrading to 1.5.5. Power on does not work (coming out of standby) on my LG TV

Thanks

Tom

PS: Amazing work on this.

**Comment by gaurav85** [comment] 2019-03-08 15:32
I am having the same issue with Power On since updating to 1.5.5.

**Comment by merdok** [comment] 2019-03-19 19:20
Version 1.5.5 had just the `config.schema.json` file added. I do not think this would cause any issues with power on.

**Comment by alexmuntean** [comment] 2019-03-19 19:49
Power on never worked for me (using this since 1.5.4). Opening tv by casting with youtube works..

**Comment by alexmuntean** [comment] 2019-03-22 12:28
I was doing some research and I believe wake on lan works if you have put mac address of that device in a packet and send it to everyone.. so I believe it's because in our config.json we don't have the correct mac address of the tv on it. I'm not sure about it. I have to check it when I get home

**Comment by alexmuntean** [comment] 2019-03-22 18:03
I tried to set the real mac Address of the TV and it seems to work. I'll play with it more..

**Comment by merdok** [comment] 2019-03-22 20:39
If you provided a fake mac address in the config file then of course power on will never work for you...

**Comment by MarkCharade** [comment] 2019-03-25 03:05
I'm having a similar issue. Had been working fine since initial releases. (Thank you!) I can control input selection and power off. Now when trying to power on  the tv doesn't react and the app will only display "powered on" status for a second before reverting to powered off state.

**Comment by Ron-Kingsley** [comment] 2019-03-25 08:07
Would you ever consider making a tutorial video walkthrough of exactly how you installed everything? I keep running into issues but I know it's from my inexperience.

**Comment by merdok** [comment] 2019-03-25 18:35
@MarkCharade @Ron-Kingsley 
The issues which you experience are probably related to your environment or network. If you have some issues with the machine homebride is running on or your home network then tere might be some issues but they are not related to this plugin...

**Comment by raulfunkie** [comment] 2019-03-25 21:19
I was having this problem and started to look through the settings of my TV. There was a "Mobile TV On" it said something among the lines of: "Allow your TV to be turned on from a mobile device app or any device on your network".

That did the trick.

**Comment by MarkCharade** [comment] 2019-03-26 03:48
@raulfunkie @merdok 

Hi there, thanks for the suggestions. I discovered the cause of the issue. The Synology (sitting on my home network) that I was running the Homebridge Docker on, was connected to the internet via VPN for privacy whilst file sharing. When I disconnected, VPN power on functionality worked again!

Can Homebridge on my home network and VPN for P2P not co-exist just fine?

**Comment by merdok** [comment] 2019-03-26 07:04
@raulfunkie 
It is described in the README that this is required for the power on feature to work :)

@MarkCharade 
I am not sure but I guess you should specify the `broadcastAdr` property. I am not sure how you configured your VPN but you need to also make sure that both the device running homebridge and the TV are on the same network (even when VPN is connected).

**Comment by zakOKLM** [comment] 2019-03-26 07:49
For those using VLANs which means your Homebridge and TV are not in the same subnet you will need to add a static arp in your router configuration. 

So let’s assume my Homebridge is on 192.168.5.x network and my TV on 192.168.2.x
Create a static arp (in my example I’m using a Unifi USG Gateway but I won’t explain how to make the config persistent through .json config)

Enter in configuration mode then
set protocols static arp 192.168.2.254 hwaddr ff:ff:ff:ff:ff:ff
Commit
Save
Exit

Where 192.168.2.254 can be any IP in the same subnet than your TV but this IP should not be assigned to any device because it won’t be routed
Do not change the hwaddr value as this is the broadcast MAC address

Go to your Homebridge configuration and add the IP (192.168.2.254 in this example) to the broadcastAdr

And voila !

I hope this will help as it helped me because I was struggling to turn on the TV with WOL :)

**Comment by merdok** [comment] 2019-03-26 21:25
@zakOKLM Thanks! I hope this will solve the problem for some people.

**Comment by vidalpascual** [comment] 2019-03-28 17:11
Exact same problem here. Everything works fine except turn the TV on from HomeKit. I have Mobile TV On set it in On and I have tried @zakOKLM configuration, but it didn't work. :(

**Comment by merdok** [comment] 2019-03-28 21:14
Make sure that your mac address is correct in the config.json. If it is correct and it still does not work then i guess you will need to check your network and see if everything is reachable.

**Closed** 2019-04-14 18:42 UTC
