### ISSUE TITLE
Siri commands

### ISSUE THREAD

**Issue by omarassil** [merdok/homebridge-webos-tv#177] opened 2019-09-27 19:48 UTC
I know this is more of a generic ios issue and not related to this plugin but there seems to be no way to get voice commands to work such as asking Siri to change input of TV or increase volume

**Comment by merdok** [comment] 2019-09-28 09:11
There is no way to change inputs or increase volume with the tv service as far as i know. You can use the volume slider (as lightbulb) or input switches to make it work with Siri.

**Comment by rooi** [comment] 2019-09-28 10:03
You can try to use siri shortcuts to trigger homekit actions and scenes with siri

**Comment by Catta1997** [comment] 2019-10-02 07:25
Volume is a light, try to ask siri to put light at "20". It works for me

**Comment by omarassil** [comment] 2019-10-04 17:55
Ok managed to use shortcuts with Siri to change TV input and normal Siri to adjust the volume (no need for Shortcuts)

**Comment by merdok** [comment] 2019-10-05 07:59
Ok, if the issue is solved for you then i am closing it.

**Closed by merdok** 2019-10-05 07:59 UTC
