### ISSUE TITLE
v2.0: Live TV not appearing in inputs list

### ISSUE THREAD

**Issue by mikebatnz** [merdok/homebridge-webos-tv#281] opened 2020-09-10 00:39 UTC
In the previous version I had "Live TV" in the inputs list
In version 2.0, Live TV no longer appears

my config:

       {
            "devices": [
                {
                    "name": "TV",
                    "ip": "192.168.1.200",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "none",
                    "channelControl": false,
                    "mediaControl": false,
                    "ccRemoteRemap": {
                        "back": "HOME",
                        "information": "MUTE"
                    },
                    "appButtons": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV Box"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        }

**Comment by merdok** [comment] 2020-09-10 05:14
Can you post a debug log?

**Comment by mikebatnz** [comment] 2020-09-10 06:27
Hi merdok
I deleted the tv from the Home app and then used the "Unpair Bridges / Cameras / TVs / External Accessories" function within Homebridge UI as well, so these logs/screenshots are for a "newly added" tv.

The (large) debug log is here: https://pastebin.com/8ZffaY9E
And screenshots of inputs when adding TV to HomeKit, plus the input spinner: https://imgur.com/a/cWMvakL
(note no Live TV in either the initial input selector when adding the tv, or the spinner)

**Comment by merdok** [comment] 2020-09-10 07:16
Thanks for the log! Helps a lot.
So you are owning a 2020 oled and it seems that something changed there, since live tv and external inputs are missing from the standard list delivered from the tv. 

Does live tv work when you add it as an appButton?

**Comment by kfalkiewicz** [comment] 2020-09-10 08:19
Got same issue (LG E9). LiveTV works as external app but doesn't show on inputs list.

PS: Also inputs list is missing HDMI inputs (like PS4).

**Comment by mikebatnz** [comment] 2020-09-10 08:31
Hi merdok,
Yes, Live TV does work as an appButton

Log:

[9/10/2020, 6:29:56 PM] [webostv] [TV] com.webos.applicationManager service - launch requested. AppId: com.webos.app.livetv, Params: {}
[9/10/2020, 6:29:56 PM] [webostv] [TV] {
  "returnValue": true
}
[9/10/2020, 6:29:56 PM] [webostv] [TV] {
  "subscribed": true,
  "appId": "com.webos.app.livetv",
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[9/10/2020, 6:29:56 PM] [webostv] [TV] App launched, current appId: com.webos.app.livetv
[9/10/2020, 6:29:56 PM] [webostv] [TV] {
  "returnValue": true,
  "state": "Active"
}
[9/10/2020, 6:29:56 PM] [webostv] [TV] TV power status changed, status:  state: Active,
[9/10/2020, 6:29:56 PM] [webostv] [TV] TV turned on!

**Comment by merdok** [comment] 2020-09-10 08:40
Interesting, I am not sure right now if it had something to do with the tv itself. Since @kfalkiewicz has the same issue and he has basically the same TV as me, I think that this might be a configuration thing on the TV. Do you both have all the necessary options in the tv preferences enabled? There are a few which need to be set to on.

**Comment by kfalkiewicz** [comment] 2020-09-10 08:46
@merdok This is How my config looks right now:
```
{
            "platform": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv"
            },
            "devices": [
                {
                    "name": "LG E9",
                    "ip": "XXX.XXX.XXX.XXX",
                    "mac": "XXX.XXX.XXX.XXX",
                    "keyFile": "/home/hoobs/.hoobs/lg3tvKeyFile",
                    "deepDebugLog": true,
                    "volumeControl": false,
                    "channelControl": false,
                    "channelButtons": [
                        {
                            "channelNumber": 1,
                            "channelName": "TVN"
                        },
                        {
                            "channelNumber": 6,
                            "channelName": "TVN24"
                        },
                        {
                            "channelNumber": 90,
                            "channelName": "Mini Mini"
                        }
                    ],
                    "ccRemoteRemap": {
                        "arrowup": "VOLUMEUP",
                        "arrowdown": "VOLUMEDOWN",
                        "arrowleft": "CHANNELDOWN",
                        "arrowright": "CHANNELUP",
                        "select": "PROGRAM",
                        "back": "BACK",
                        "playpause": "PAUSE",
                        "information": "TELETEXT"
                    }
                }
            ]
        },
```

**Comment by mikebatnz** [comment] 2020-09-10 08:54
Same for me; have not updated the settings on the tv itself

**Comment by merdok** [comment] 2020-09-10 08:57
Config looks ok and it should not be a cause of the issue.

It was working previously because you had to manually add the inputs to the spinner, now the spinner is populated automatically based on what the tv delivers. For some reason in your cases the tv does not include the live tv and external inputs. We would need to find out why is that the case, especially since I also have a 9 series oled and my tv delivers all the data. For this reason I suspect that maybe this is a configuration issues with the tv itself. It would be nice if you could play around with the settings a little and see if something changes.

**Comment by kfalkiewicz** [comment] 2020-09-10 09:25
Hmm will look at this.

**Comment by marioPS** [comment] 2020-09-10 10:04
Hi, and thanks again for your hard work.
Yes, there are a few issues
Pros: Config worked without change.
Cons: No inputs. Settings button doesn't work.
<img width="304" alt="Screen Shot 2020-09-10 at 7 59 59 PM" src="https://user-images.githubusercontent.com/11381244/92715403-c560e500-f3a0-11ea-9853-dd15f06fc1e1.png">
<img width="314" alt="Screen Shot 2020-09-10 at 7 59 45 PM" src="https://user-images.githubusercontent.com/11381244/92715421-c98d0280-f3a0-11ea-8fa6-ceee3a48bcba.png">

**Comment by kfalkiewicz** [comment] 2020-09-10 10:11
@marioPS Open settings of TV device (not group as all) and post a screenshot of list of inputs you see there.
At the start no input is selected, so that's why this list is empty.

**Comment by mikebatnz** [comment] 2020-09-10 10:19
Hi @merdok 

What do you think about a new optional 'additionalInputs' config option?

This could be used to append any user-defined inputs to the input spinner if they were not returned by the TV
eg.
                    "additionalInputs": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "PS4"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Switch"
                        }
                    ]

**Comment by merdok** [comment] 2020-09-10 10:59
@marioPS you need to first enable some inputs under the preferences. Does pressing the setting throw an error?

@mikebatnz that would be a solution. I am also thinking of checking if live tv and external inputs are in the list from the tv and if not then add them. 

Anyway, I would still like to know why those are missing in the inputs retrieved from the tv.
Can you guys confirm that it is only live tv and the external inputs which are missing or are there any other apps which are missing in the spinner which you have on the tv? You can check all your apps in the Home Screen on your tv.
Also @marioPS and @kfalkiewicz could you also please post a debug log like @mikebatnz did so i can compare and try to spot any differences...

**Comment by marioPS** [comment] 2020-09-10 11:00
@kfalkiewicz That is exactly what I did ... I manually added inputs, but they still did not appear.

**Comment by mikebatnz** [comment] 2020-09-10 11:11
Hi @merdok 
I've confirmed that all of the apps in the home bar do appear in the input spinner.
Also downloaded a new app from the LG store and it appeared immediately in the Home app

**Comment by merdok** [comment] 2020-09-10 11:19
@mikebatnz that at least sounds and is the correct behavior.
Do you also have a live tv app at the Home Screen on your tv? Or any apps for your external Inputs?

**Comment by kfalkiewicz** [comment] 2020-09-10 11:23
@merdok
1) Checked LG settings. All things related to external control is enabled as before.
2) My webOS version is 04.80
3) Yes all "normal apps" are visible on Inputs list. Only thing missing is LiveTV (with isn't treated as app maybe) and external inputs (like HDMI 3 with is configured as PS4 console in LG settings).
4) Live TV and external Inputs doesn't show in LG Home App selection (never was there)

**Comment by mikebatnz** [comment] 2020-09-10 11:46
Hi @merdok 
Here's a pic of the home bar on mine - TV is a separate thing to the left of the other apps
https://imgur.com/EOJfj5m

**Comment by kfalkiewicz** [comment] 2020-09-10 11:48
Same as @mikebatnz (external HDMI is hidden behind 2nd icon if I remember correctly)

**Comment by merdok** [comment] 2020-09-10 11:57
Oh, now we are getting closer. So I just noticed my tv is an oled 8 series, so it seems like since the 9 series something changed. It seems like that live tv and external inputs are not dedicated apps anymore. I noticed from @mikebatnz log that the live tv app is hidden. I guess lg made this separate bar there on the left side to hold those things. What does the other buttons do?

Besides that, can you open the inputs app on your tv(you can use the remote), can you configure the inputs there to appear on the Home Screen?

**Comment by kfalkiewicz** [comment] 2020-09-10 12:15
No you cannot show inputs on home screen.
Screenshots:
![7647D806-DB50-4433-B327-A9F9311F30FE](https://user-images.githubusercontent.com/1431712/92727785-f83eb500-f36f-11ea-94f3-41e796033c57.jpeg)
![F2D6F39D-58DF-4E4E-9184-A62952E8403C](https://user-images.githubusercontent.com/1431712/92727798-fd9bff80-f36f-11ea-8bcd-d1609303986a.jpeg)

**Comment by mikebatnz** [comment] 2020-09-10 12:17
Hi @merdok 

The 4 apps locked to the left of my Home Screen are:

1. Search (com.webos.app.recommend)
2. Home Dashboard (com.webos.app.homeconnect)
3. TV (com.webos.app.livetv)
4. Recent

**Comment by merdok** [comment] 2020-09-10 12:29
@mikebatnz and @kfalkiewicz thanks for the infos. I guess this is a change which lg made since webos 4.5

The fix should be straight forward, I simply do a check if those apps are missing in the list from the tv and will add them if they are not there. Live Tv and external inputs should be always there.

How about the home dashboard app, it seems that this also has no app tile so it is missing on the spinner. Is that something you would also like to have in the spinner?

**Comment by kfalkiewicz** [comment] 2020-09-10 12:34
Not really 😜. I dont use this feature (home dashboard).

**Comment by mikebatnz** [comment] 2020-09-10 12:38
@merdok thank you.
I am not sure about the Home Dashboard, it is not really an input

If the livetv and/or inputs are going to be added to the spinner, would it be possible to see if there is a custom name set up for them on the TV?

For example, my HDMI 1 input was renamed to "Lounge ATVHD" and this appears in the log as "osdName"

`
  {
    "id": "HDMI_1",
    "appId": "com.webos.app.hdmi1",
    "name": "Apple TV HD",
    "subList": [
      {
        "id": "SIMPLINK",
        "portId": 1,
        "uniqueId": 4,
        "vendorId": 4346,
        "physicalAddress": 4096,
        "depth": 1,
        "osdName": "Lounge ATVHD",
        "cecpDevType": 4,
        "cecpNewType": 9
      },`

**Comment by merdok** [comment] 2020-09-10 12:51
Well, this is already included, but in the case of a subList (which you show) this is a little bit complicated. In the case above the name "Apple TV HD" will be used because this is the actual name of the input. As i only can set one name, i always use the input name. As you can see a subList item has no appId so you cannot directly navigate to it hence it would be not a good ideas to use that name. 
BTW, you can also rename the inputs in the Home app, this will only take effect in the home app and will be preserved in a config file so it will stay as you name it 😉

**Comment by merdok** [comment] 2020-09-10 21:02
Please check version 2.0.1. That should make the missing appear now.

**Comment by mikebatnz** [comment] 2020-09-10 23:35
Hi @merdok 
I deleted the TV and re-added it.
Unfortunately now there are 3 "Live TV" switches and no additional entries in the input spinner

https://imgur.com/a/gqa8TV5

**Comment by merdok** [comment] 2020-09-11 04:26
Could you provide a new debug log?

**Comment by mikebatnz** [comment] 2020-09-11 05:22
Hi @merdok 
Sorry, yes :)

Here we are: https://pastebin.com/uZ99hPGQ

I also filtered just the first lines of each log entry here: https://pastebin.com/8zmSYqsX

In this, I can see the new lines to add the missing livetv and inputs...
```[9/11/2020, 3:07:16 PM] [webostv] [TV] Live TV app is missing in the launch points list, adding it manually!
[9/11/2020, 3:07:16 PM] [webostv] [TV] Input com.webos.app.externalinput.av1 is missing in the launch points list, adding it manually!
[9/11/2020, 3:07:16 PM] [webostv] [TV] Input com.webos.app.hdmi1 is missing in the launch points list, adding it manually!
[9/11/2020, 3:07:16 PM] [webostv] [TV] Input com.webos.app.externalinput.component is missing in the launch points list, adding it manually!
[9/11/2020, 3:07:16 PM] [webostv] [TV] Input com.webos.app.hdmi3 is missing in the launch points list, adding it manually!
[9/11/2020, 3:07:16 PM] [webostv] [TV] Input com.webos.app.hdmi4 is missing in the launch points list, adding it manually!
[9/11/2020, 3:07:16 PM] [webostv] [TV] Input com.webos.app.hdmi2 is missing in the launch points list, adding it manually!````

...but then there is a subsequent "got new launch points" log entry, without subsequent adding of livetv, inputs..?

````[9/11/2020, 3:07:18 PM] [webostv] [TV] Got new launch points list from tv!````

**Comment by merdok** [comment] 2020-09-11 06:04
Thanks! First off, nice job with the log 👍 if everyone would provide log like that then it would be easier to debug stuff😅

Anyway, from the log I do not see anything wrong. Maybe this is simply a caching issue? Can you try force kill the home app since it sometimes gets stuck. Also try to remove the webos config files. They should be under .webosTv

**Comment by mikebatnz** [comment] 2020-09-11 07:16
Hi @merdok 
No problem, thank you for making a great plugin and for helping so quickly with this.

I'm afraid that this didn't resolve it :-(

I did the following:

1. killed the Home app
2. removed the TV from Home
3. removed the .webosTv directory
4. used _Unpair Bridges / Cameras / TVs / External Accessories_ in Homebridge UI X
5. restarted Homebridge
6. re-added the TV in the Home app

I can see that the plugin has recreated the .webosTv directory, with 2 files within:
```
-rw-r--r-- 1 pi pi   773 Sep 11 17:14 inputsAvailable_64956cbdca35
-rw-r--r-- 1 pi pi   891 Sep 11 17:15 inputsConfg_64956cbdca35```

Unfortunately, within **inputsAvailable_64956cbdca35** I can see that LiveTV and the inputs are still missing :-(

```json
[{"appId":"com.swm.7plus","name":"7plus"},
{"appId":"abc","name":"ABC iview"},
{"appId":"amazon.alexapr","name":"Amazon Alexa"},
{"appId":"com.apple.appletv","name":"Apple TV"},
{"appId":"com.webos.app.igallery","name":"Art Gallery"},
{"appId":"com.disney.disneyplu
s-prod","name":"Disney+"},
{"appId":"com.webos.app.discovery","name":"LG Content Store"},
{"appId":"com.webos.app.music","name":"Music"},
{"appId":"netflix","name":"Netflix"},
{"appId":"com.webos.app.photovideo","name":"Photo & Video"},
{"appId":"cdp-30","name":"Plex"},
{"appId":"sbs","name":"SBS on Demand"},
{"appId":"com.webos.app.sportsteamsettings","name":"Sports Alert"},
{"appId":"stan.webos2","name":"Stan"},
{"appId":"com.webos.app.browser","name":"Web Browser"},
{"appId":"youtube.leanback.v4","name":"YouTube"}]
```

**Comment by merdok** [comment] 2020-09-11 13:28
Did you force kill the home app after the setup? Also did you configure your I put spinner with apps from the accessory preferences?

**Comment by mikebatnz** [comment] 2020-09-11 23:15
Hi @merdok 

I hope you don't mind but I dug around in the **lib/LgTvController.js** file on my local rpi to see if I could see what was happening

I saw that you added **checkBasicInputs()** in **setupTvConnection()**, which adds the missing livetv and inputs:

```
  setupTvConnection() {
    this.getTvInformation().then(() => {
      this.logInfo('Got TV information');
      this.checkBasicInputs(); // webos 4.5 is mising some basic inputs so make sure that they are present
```

The trouble is, after the initial connection, my TV sends an 'updated' launchpoints list (which is actually the same as the initial list, but that is irrelevant 😄 )

This triggers **subscribeToLaunchPointsListChange()**, and in this, **checkBasicInputs()** is not called:

```
  async subscribeToLaunchPointsListChange() {
    return this.tvSubscribe(WEBOS_URI_LAUNCH_POINTS, null, (err, res) => {
      if (res && res.launchPoints && Array.isArray(res.launchPoints)) {
        this.launchPointsList = this.parseLaunchPoints(res.launchPoints);
        this.logDebug(`Got new launch points list from tv!`);
```

So as an experiment, I added **checkBasicInputs()** function to **subscribeToLaunchPointsListChange()**, just after **parseLaunchPoints**, ie.
```
  async subscribeToLaunchPointsListChange() {
    return this.tvSubscribe(WEBOS_URI_LAUNCH_POINTS, null, (err, res) => {
      if (res && res.launchPoints && Array.isArray(res.launchPoints)) {
        this.launchPointsList = this.parseLaunchPoints(res.launchPoints);
        this.checkBasicInputs(); //ADDED THIS
        this.logDebug(`Got new launch points list from tv!`);
```

and now I am getting the full list of apps+livetv+inputs in the input spinner

**Comment by merdok** [comment] 2020-09-12 05:45
Oh, you are right! I missed that place😅 Thanks for debugging that and finding the right place. I will add that and submit an update. But it will take 1 week till I can release the update because I have currently no access to a PC.

**Comment by marioPS** [comment] 2020-09-13 09:22
Thanks for the tip @mikebatnz ! 
I performed the same mod (from root /usr/local/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js on my mac)o
Now all the inputs are all in Home:
<img width="300" alt="Screen Shot 2020-09-13 at 7 16 23 PM" src="https://user-images.githubusercontent.com/11381244/93014597-aa3ae300-f5f5-11ea-97be-39d695f10d76.png">
<img width="297" alt="Screen Shot 2020-09-13 at 7 16 02 PM" src="https://user-images.githubusercontent.com/11381244/93014599-adce6a00-f5f5-11ea-84bd-3eb013128cb6.png">
<img width="297" alt="Screen Shot 2020-09-13 at 7 15 38 PM" src="https://user-images.githubusercontent.com/11381244/93014602-aeff9700-f5f5-11ea-98d4-9ffa33af1fed.png">
Next, to work out what all the other bits do: I can't get "Control Centre Remote" to do anything despite it being configured, and Siri will only change the volume *after* I've changed channels ...
@merdok - looking forward to the adventure!
-- marioPS

**Comment by merdok** [comment] 2020-09-13 12:07
@marioPS what is wrong with the control center remote for you?

**Comment by marioPS** [comment] 2020-09-14 08:42
Hi @merdok, and thanks for your reply.
I have no idea of what the "control centre remote" is: I've had a big search in the Home app (macOS & iOS), and the Hombridge web interface.
Maybe I've gone covid-crazy, but I have no idea what it is or where to find it.
Can you please send screenshots/directions on how to get there?
BTW: I added the settings to my config, but did not detect ant change.
Thanks for the help so far, and this amazing plug in.

MarioPS

**Comment by mikebatnz** [comment] 2020-09-14 08:46
Hi @marioPS
It's this button in the iOS control centre

![image](https://user-images.githubusercontent.com/59633951/93064196-960ce980-f6ba-11ea-97b4-85a0d78af9b6.jpeg)

**Comment by kfalkiewicz** [comment] 2020-09-14 08:47
@marioPS 
You can add it to Control Center (iOS). See screenshots below:
![IMG_3875](https://user-images.githubusercontent.com/1431712/93064078-68eb1780-f677-11ea-8eec-fd191a555cd6.PNG)
![IMG_3876](https://user-images.githubusercontent.com/1431712/93064110-70122580-f677-11ea-82d8-8f2fd7a6c481.PNG)

**Comment by marioPS** [comment] 2020-09-14 09:00
Wow! Thanks for the fast tutorial! It had never occurred to me that the TV would present as an Apple TV to the remote app (via the control center).

I have a new toy to play with.

BTW: In this mode, the volume buttons work, making the code example in the wiki redundant ...

Tanks again - you people are legends!

marioPS

**Comment by merdok** [comment] 2020-09-14 17:01
The code example is used to created extra switches for volume, it has nothing to do with the cc remote.

**Comment by marioPS** [comment] 2020-09-15 03:02
That's good to know - but when the device is selected in CC (either via the swipe down, or accessing the remote via Home app), one can use the iPhones hardware buttons to control the LG TV's volume.

Either way, that's pretty cool!

**Comment by microsaft82** [comment] 2020-09-16 05:29
Hi guys,
Fun reading this :)
I’ve got the same issue I guess. The spinner only gets 4 random inputs and I was going mad until I found this. Very reassuring and happy to read I’m not the only one. Very cool you guys came together and found the solution. Looking forward to the update/fix. 
And many thanks to the creator, you rule!
Greetings Mike

**Comment by merdok** [comment] 2020-09-18 20:29
I will include the fix most probably tomorrow, finally i have access to my PC again and can do some coding :)

**Comment by microsaft82** [comment] 2020-09-18 20:34
That’s great. Thanks for the update.

**Comment by merdok** [comment] 2020-09-18 21:07
Should be fixed in version 2.0.2. Can you guys please confirm?

**Comment by vahov** [comment] 2020-09-19 01:00
Yes, the inputs are back. They appeared after update and then turning on the TV. Thank you!

**Comment by mikebatnz** [comment] 2020-09-19 01:04
Can confirm the inputs now appear :) thank you @merdok!!

**Comment by microsaft82** [comment] 2020-09-19 05:11
I still got only 4 inputs. Maybe I need to reset something? Or maybe I
should not enter inputs in the config as it overwrites the generated inputs?

**Comment by microsaft82** [comment] 2020-09-19 05:19
Scratch that. Sorry I missed I had to go into the tv settings in home app
to mark all the inputs I wanted to show.

Very nice work on the plug-in man! We use it every day with pleasure.

**Comment by merdok** [comment] 2020-09-19 05:48
@microsaft82 heh yeah, you can configure yourself the input spinner from the tv settings now. All the inputs should be there, per default only live tv and external inputs are selected.

@mikebatnz ans @vahov thanks for confirming, glad that now all works also on the newer TVs😀

BTW, what do you guys think about showing only the basic inputs per default? Maybe it would be better to simply show all the inputs per default in the input spinner? I didn't want to put everything there at start since it could be to much so I just decided to put the basic inputs which everyone should have as default.

**Comment by microsaft82** [comment] 2020-09-19 05:55
Maybe not all inputs by default, but maybe a little more?
Like Netflix, Amazon prime and YouTube are probably used by most of the
users?

Gr Mike

**Comment by merdok** [comment] 2020-09-19 20:50
Not sure about Netflix, Amazon prime, Disney+ or AppleTV+. I mean not all people use them so i do not want to force them to have those apps preconfigured. On the other side also not all people use Live TV...

**Comment by marioPS** [comment] 2020-09-20 08:34
My vote: "Live TV" and each of the HDMI inputs as per the users naming scheme.
That's the minimum one would expect segueing from a normal remote to HomeKit.

**Comment by merdok** [comment] 2020-09-20 10:35
@marioPS so basically as it is right now?

**Comment by marioPS** [comment] 2020-09-20 10:38
So far so good for me.
Are there any procedures you’d like me to test?
Just let me know!

**Comment by merdok** [comment] 2020-09-20 10:51
Okay 👍 

You could try to install or remove an app on the TV and see if the added/removed app shows up/ or gets removed from the input list. This should actually happen without the need to restart homebridge.

**Comment by marioPS** [comment] 2020-09-21 00:03
Hi @merdok - I can confirm adding and deleting apps is dynamic and does not require rebooting either homebridge, homekit app (iOS) or device (LGTV):
• Added Spotify
• Added Twitch
• Checked iOS Home app LG TV inputs - both added
• Removed Twitch app
• Checked iOS Home app LG TV inputs - Twitch removed.
I hope this helps!
BTW: LG's own iOS app did not dynamically update - adding inputs breaks it until reboot …

**Comment by merdok** [comment] 2020-09-21 05:12
That sounds good! Thanks for testing that😀

**Closed** 2020-09-21 05:11 UTC
