### ISSUE TITLE
[Feature Request] Device Type TV

### ISSUE THREAD

**Issue by vmax77** [merdok/homebridge-webos-tv#87] opened 2019-01-10 22:24 UTC
Hi

I know this is early, but it would nice if the TV was detected as type TV

![image](https://user-images.githubusercontent.com/4384278/51000969-6966fe80-14e3-11e9-85be-428237de0319.png)

Thank you

**Comment by merdok** [comment] 2019-01-10 22:46
When this will be added into HomeKit then I will implement it. I guess this will be available not sooner then with iOS13 so it is still months away...

**Comment by creinhart** [comment] 2019-01-24 21:38
Looks like this Support just appeared in the latest iOS 12.2 beta today. Would be great once this plugin is recognized as a TV in HomeKit.

**Comment by akseez** [comment] 2019-01-24 23:32
Here’s a post of someone showing how it works: 
https://mobile.twitter.com/KhaosT/status/1088521851750379520 

Also, what’s available in the Remote app: 
https://mobile.twitter.com/KhaosT/status/1088540954892464128

**Comment by KhaosT** [comment] 2019-01-25 06:06
Supports for TV has been added to hap-nodejs and homebridge :) Please let me know if you have any question about the new services.

https://github.com/KhaosT/HAP-NodeJS/commit/243c112abee13346007db358b13b5bbeda75e0af
https://github.com/nfarina/homebridge/commit/27073def733ac94897c57b178a85ee83be46c03c

**Comment by m11rphy** [comment] 2019-01-25 10:49
I came to see if you was looking at this seems as though you already are, can't wait to see what you come up with. Also thank you for all your work on this plugin its really great

**Comment by Hiddecollee** [comment] 2019-01-25 13:31
> Will keep an eye on it 👍

Are you working on it? I would love to have it.

**Comment by mcnahum** [comment] 2019-01-25 16:19
I think everybody was thinking the same with this new feature, that will be really great to have it.

**Comment by merdok** [comment] 2019-01-25 17:27
Finally they added a tv device type. I will definitely work on this. 

@KhaosT did you add those services? Did you try those services with iOS12.2 Beta? Maybe i will install the beta over the weekend and try it out.

**Comment by KhaosT** [comment] 2019-01-25 17:31
@merdok Yeah, TV support is enabled in iOS 12.2 beta in Home and Control Center Remote.

**Comment by merdok** [comment] 2019-01-25 18:01
I guess there should not be any issues add the TV service to HomeKit. About the Control Center Remote i am not sure if i will be able to add this. Need to check how this works...

**Comment by creinhart** [comment] 2019-01-25 18:30
TV service is good enough for me, but whatever you can do we appreciate it. Especially since LG won’t update previous models with homekit support. I’m running the 12.2 beta now. Pretty cool being able to tell Siri to play a specific movie on the Apple TV and she just does it.

**Comment by merdok** [comment] 2019-01-25 22:35
@KhaosT does the Control Center Remote also use HomeKit to send the commands to the TV?

**Comment by Ben305** [comment] 2019-01-25 22:38
I have already made some progress, buttons UP, DOWN, LEFT, RIGHT, ENTER, BACK, and EXIT are working.

**Comment by merdok** [comment] 2019-01-25 22:56
Good to know that the remote also goes through HomeKit. Will be working on the TV service over the weekend.

**Comment by KhaosT** [comment] 2019-01-26 02:08
@merdok Yeah, the remote part sends the command via [Remote Key](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes-Television.js#L210) characteristic. On webOS side I think you already have the button event in current code.

**Comment by merdok** [comment] 2019-01-26 08:15
@KhaosT Yep, tested it and it works fine. 

How about the REWIND, FAST_FORWARD, NEXT_TRACK, PREVIOUS_TRACK buttons, i do not see them on the remote... where are they located? 
Also there are Characteristics like PictureMode or Brightness which i could not find anywhere in the app. Are they just missing in the current beta?

**Comment by KhaosT** [comment] 2019-01-26 19:11
Yeah I wasn’t able to have those show up right now, and it doesn’t look like it’s being used in current beta. The only additional characteristic Home app handles is the power mode one, which is really strange…

Hopefully those are tied to current media state characteristic, and a now playing screen can show up with ability to control playback in future beta

**Comment by KhaosT** [comment] 2019-01-26 19:41
Huh add to linked service is the right way to do this… did you set identifier correctly to all input sources?

**Comment by merdok** [comment] 2019-01-26 19:47
Testing currently with one input source. Looks like follows:

''
var inputHDMI1 = new Service.InputSource("hdmi1", "HDMI 1");

inputHDMI1
.setCharacteristic(Characteristic.Identifier, 1)
.setCharacteristic(Characteristic.ConfiguredName, "HDMI 1")
.setCharacteristic(Characteristic.IsConfigured, Characteristic.IsConfigured.CONFIGURED)
.setCharacteristic(Characteristic.InputSourceType, Characteristic.InputSourceType.HDMI);

this.tvService.addLinkedService(inputHDMI1);

''

This does not want to show up for me under Input in the Home app

**Comment by KhaosT** [comment] 2019-01-26 19:53
@merdok did you also include `inputHDMI1` in the array you returned for services?

**Comment by merdok** [comment] 2019-01-26 19:57
@KhaosT Yes, if add it there then it appears as a new switch on the Home dashboard, but still not as an input for the TV.

**Comment by KhaosT** [comment] 2019-01-26 19:59
@merdok is it possible for you to push the current code you have to a branch or something? If you return it in the services array, and add it as a linked service to the tv service itself, Home app should be able to see it and show you an input switch, instead of a separate tile.

**Comment by merdok** [comment] 2019-01-26 20:06
@KhaosT This is how the relevant code currently looks:

```
this.tvService = new Service.Television(this.name, "tvService");
	
this.tvService
	.setCharacteristic(Characteristic.ConfiguredName, this.name);
		
this.tvService
	.setCharacteristic(Characteristic.SleepDiscoveryMode, Characteristic.SleepDiscoveryMode.ALWAYS_DISCOVERABLE);
		
this.tvService
	.getCharacteristic(Characteristic.Active)
        .on('get', this.getPowerState.bind(this))
        .on('set', this.setPowerState.bind(this));
		
this.tvService
	.setCharacteristic(Characteristic.ActiveIdentifier, 1);
	
this.enabledServices.push(this.tvService);
	  
	  
var inputHDMI1 = new Service.InputSource("hdmi1", "HDMI 1");

inputHDMI1
	.setCharacteristic(Characteristic.Identifier, 1)
	.setCharacteristic(Characteristic.ConfiguredName, "HDMI 1")
	.setCharacteristic(Characteristic.IsConfigured, Characteristic.IsConfigured.CONFIGURED)
	.setCharacteristic(Characteristic.InputSourceType, Characteristic.InputSourceType.HDMI)
	.setCharacteristic(Characteristic.CurrentVisibilityState, Characteristic.CurrentVisibilityState.SHOWN);
	  
	this.enabledServices.push(inputHDMI1);
	this.tvService.addLinkedService(inputHDMI1);

```

This does creates a separate tile on in the Home app instead an input source for the tv tile.

**Comment by KhaosT** [comment] 2019-01-26 20:10
Overall it looks right... let me try using this on my side and see if I can reproduce it.
The `ActiveIdentifier` characteristic in TV Service indicates what's the current active input source the TV is using. Each `InputSource` service has an `Identifier` characteristic which the value should be unique. When HomeKit want to change input source, it will write to `ActiveIdentifier` with the identifier matching the `InputSource`'s `Identifier`

**Comment by merdok** [comment] 2019-01-26 20:16
Please let me know your finding. I already got everything to work except the input sources...

Ok, got it! So this is related to the input sources. So i assume the setter will be called as soon as an input source is selected?

**Comment by KhaosT** [comment] 2019-01-26 20:19
@merdok I tried the same code and it's working for me... https://gist.github.com/KhaosT/b0c7b481d7106025f061a1c621cd2fa4

Yup, and if the input change from the TV side, you can also update `ActiveIdentifier` so Home app will show the one that's currently on TV.

**Comment by KhaosT** [comment] 2019-01-26 20:33
🤔 have you tried remove homebridge from HomeKit and add it back again? Maybe it’s cache?

**Comment by Ben305** [comment] 2019-01-26 20:36
@merdok You have to implement it like this

`var inputHDMI1 = new Service.InputSource("hdmi1", "HDMI 1");

    inputHDMI1
        .setCharacteristic(Characteristic.Identifier, 1)
        .setCharacteristic(Characteristic.ConfiguredName, "HDMI 1")
        .setCharacteristic(Characteristic.IsConfigured, Characteristic.IsConfigured.CONFIGURED)
        .setCharacteristic(Characteristic.InputSourceType, Characteristic.InputSourceType.HDMI);

    this.tvService.addLinkedService(inputHDMI1);
    this.enabledServices.push(this.tvService);
    this.enabledServices.push(inputHDMI1);`

It's important to add the input as linked service *and* add to the service array.

**Comment by merdok** [comment] 2019-01-26 20:40
@KhaosT But if this would be a cache issue then i guess i would not be able to use any of the TV services since they all were added at the sam time right?

@Ben305 tried also that. Still does not work as expected. 

Strange issue...

**Comment by Ben305** [comment] 2019-01-26 20:41
@merdok Pushed my branch which is working here...

**Comment by KhaosT** [comment] 2019-01-26 20:45
Another question, what’s your node version?

**Comment by merdok** [comment] 2019-01-26 20:46
@Ben305 that does not work for me
@KhaosT v8.15.0

**Comment by KhaosT** [comment] 2019-01-26 20:50
I’m running v10.15.0 here… not sure if that matters.
By cache issue, I mean maybe HomeKit will only try to setup TV input for an accessory if it never seen it before…so if you are progressively tinkering the services, maybe that confuses HomeKit…

**Comment by merdok** [comment] 2019-01-26 20:59
Oh, yes that was the issue here. Some kind of home cache probably. I did change the tv service identifier and the input source identifier and it work now... Afterwards i could change them back to the original ones and it still now works 👍

**Comment by Hiddecollee** [comment] 2019-01-26 21:00
So everything works now?

**Comment by merdok** [comment] 2019-01-26 21:09
Everything looks good. I will work on the input sources now and then it should be ready.

**Comment by Hiddecollee** [comment] 2019-01-26 21:40
When you are done, you publish it and then we will be able to add this to our homebridge?

**Comment by merdok** [comment] 2019-01-26 21:51
Yes, as long as you are on iOS12.2 beta then you will be able to enable and use the new services.

**Comment by m11rphy** [comment] 2019-01-26 21:53
Hey merdok great work as always much appreciated. I ha e 3 LG TVs will it be possible to add all 3?

**Comment by merdok** [comment] 2019-01-26 22:07
I cannot test it by myself since i have only 1 TV, but I do not see any reason why it should not work. 
After it is released you can test it and let me know :)

**Comment by Hiddecollee** [comment] 2019-01-26 22:10
When do you think you will release it?

**Comment by Hiddecollee** [comment] 2019-01-26 22:31
Okay, so impatient ahhahaha

**Comment by Hiddecollee** [comment] 2019-01-27 10:35
What tv do you have?

**Comment by merdok** [comment] 2019-01-27 10:53
HomeKit TV integration can now be enabled in the latest release. Please test ist and let me know how it works :)

**Comment by Hiddecollee** [comment] 2019-01-27 11:34
Hey, when I add the code I just get all different switches but no TV.. what could be the problem?
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:40",
		"pin": "031-45-154"
	},


	"accessories": [{
		"accessory": "Toon",
		"name": "Toon",
		"username": "acollee@haaglandenhypotheek.nl",
		"password": "Hidde2001!"
	}, {
		"accessory": "webostv",
		"name": "LG B7",
		"ip": "192.168.178.52",
		"mac": "7C:1C:4E:E8:85:90",
		"keyFile": "/home/pi/.homebridge/lgtvKeyFile",
		"pollingInterval": 10,
		"tvService": true,
		"inputs": [{
				"appId": "youtube.leanback.v4",
				"name": "YouTube"
			},
			{
				"appId": "youtube.leanback.v4",
				"name": "Photo Video"
			}
		],
		"volumeControl": "switch",
		"mediaControl": false,
		"appSwitch": [
			"com.webos.app.photovideo",
			"youtube.leanback.v4",
			"com.webos.app.hdmi2",
			"com.webos.app.externalinput.component"
		],
		"channelButtons": [3, 5, 7, 8],
		"notificationButtons": [
			"Motion detected - living room",
			"Motion detected - kitchen"
		],
		"remoteControlButtons": [
			"HOME",
			"LIST",
			"EXIT"
		]
	}]
}
`

**Comment by merdok** [comment] 2019-01-27 11:42
Are you on iOS 12.2 Beta?
channelButtons, notificationButtons, remoteControlButtons and volumeControl will still appear as switches if enabled since there is no way in the current iOS beta to control them from the remote control.

**Comment by Hiddecollee** [comment] 2019-01-27 11:58
You

> Are you on iOS 12.2 Beta?
> channelButtons, notificationButtons, remoteControlButtons and volumeControl will still appear as switches if enabled since there is no way in the current iOS beta to control them from the remote control.

Could I get rid of the switches? I don't really use them. And you can already control the volumeControl with the Remote in control center.

**Comment by Hiddecollee** [comment] 2019-01-27 12:08
And what about the inputs, I only use HDMI 1 and Live TV, how can I get rid of the rest of them?

**Comment by merdok** [comment] 2019-01-27 12:16
Please read the README, you can disable whichever services you want...
Most probably in some later iOS betas you will be able to hide the inputs from the list which you don't use.

**Comment by creinhart** [comment] 2019-01-27 12:31
Works perfectly! Thank you! I have 2 LG TVs running with the new TV service now. As a side note, make sure to get rid of the appswitch if you don't want other switches. I have no spare switches at all. Just the TVs themselves.

**Comment by merdok** [comment] 2019-01-27 12:57
@Ben305 you have to manually disable the services that you do not want. `"mediaControl": false ` will just disable the media control service.

@creinhart Good to hear 👍 
The appSwitch is completely ignored when using the new tv services. It is basically replaced by inputs.

**Comment by m11rphy** [comment] 2019-01-27 13:13
@creinhaet could I see your config for 2 TVs please

**Comment by m11rphy** [comment] 2019-01-27 13:15
> Works perfectly! Thank you! I have 2 LG TVs running with the new TV service now. As a side note, make sure to get rid of the appswitch if you don't want other switches. I have no spare switches at all. Just the TVs themselves.

Could I see your config for 2 TVs please?

**Comment by creinhart** [comment] 2019-01-27 13:45
> > Works perfectly! Thank you! I have 2 LG TVs running with the new TV service now. As a side note, make sure to get rid of the appswitch if you don't want other switches. I have no spare switches at all. Just the TVs themselves.
> 
> Could I see your config for 2 TVs please?

`

  "accessories": [
    {
      "accessory": "webostv",
      "name": "LGTV",
      "ip": "192.168.0.148",
      "mac": "00:51:ED:35:xx:xx",
      "keyFile": "/Users/xx/.homebridge/persist/lgtvKeyFile",
      "pollingInterval": 10,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    },
      

{
      "accessory": "webostv",
      "name": "LGTV2",
      "ip": "192.168.0.112",
      "mac": "20:3D:BD:FA:xx:xx
      "keyFile": "/Users/xx/.homebridge/persist/lgtvKeyFile2",
      "pollingInterval": 10,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    }
  
]

}`

**Comment by merdok** [comment] 2019-01-27 15:33
@lboue this is most probably a bug in the current iOS beta. You just need to force close the Home app  if that happens and reopen it again, also restarting homebridge does help. Has the same issues...

**Comment by m11rphy** [comment] 2019-01-27 17:36
hi guys, can you help with this error please?

TypeError: Service.Television is not a constructor
    at webosTvAccessory.prepareNewTvService (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:270:22)
    at new webosTvAccessory (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:120:14)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by HunterJKirby** [comment] 2019-01-27 17:37
You need to update nodeJS

**Comment by m11rphy** [comment] 2019-01-27 17:41
> You need to update nodeJS
> […](#)

Thanks I've updated but now get this error 

Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:777:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/local/lib/node_modules/homebridge/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/ed25519-hap/index.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)

**Comment by HunterJKirby** [comment] 2019-01-27 17:42
Uninstalling then reinstalling homebridge fixes this!

**Comment by m11rphy** [comment] 2019-01-27 17:45
> Uninstalling then reinstalling homebridge fixes this!
> […](#)

now I'm getting this error

**Comment by merdok** [comment] 2019-01-27 18:12
Now you have some permission errors not related to this plugin. You would need to fix your environment.

**Comment by m11rphy** [comment] 2019-01-27 18:32
> Now you have some permission errors not related to this plugin. You would need to fix your environment.



> @m11rphy try sudo npm install -g --unsafe-perm homebridge

Guys I'm reformatting my Mac mini and starting again,

To confirm I should install 11.8.0? 

to install home bridge should I use: 
sudo npm install -g --unsafe-perm homebridge
or
sudo npm install -g homebridge?

im using MacOS Mojave

**Comment by Ben305** [comment] 2019-01-27 18:35
Best solution would be a node environment where sudo isn‘t needed for installation of globally installed packages.

**Comment by m11rphy** [comment] 2019-01-27 18:39
> Best solution would be a node environment where sudo isn‘t needed for installation of globally installed packages.

in English lol?

**Comment by m11rphy** [comment] 2019-01-27 19:33
Guys I have whipped my Mac reinstalled everything but when I try and add home bridge to the home app, I get a error can not add accessory. Any ideas?

**Comment by lboue** [comment] 2019-01-27 19:34
In my case closing the Home app and reopen it again fixed the issue. Thanks :)

**Comment by m11rphy** [comment] 2019-01-27 19:55
Guys please help, I restart my Mac and iPhone and I can't add home bridge to home now. Even tried to add on my iPad

**Comment by KhaosT** [comment] 2019-01-27 20:01
@m11rphy can you file an issue at https://github.com/nfarina/homebridge/issues and provide logs from homebridge in there? The issue is unlikely plugin related, so there is no need to spam everyone in the thread 😅

**Comment by 2nm** [comment] 2019-01-27 20:43
Hey, just wondering did anyone have an issue where you can’t turn a TV on with the 12.2 service? Got Two OLED TVs identical with identical accessory declarations and setup (though not name, mac, IP, keyfile) one works one doesn’t.  
And wondering when using the remote from control centre the back and exit buttons don’t seem to do anything, and is there meant to be a channel changer or is that not implemented? 

Thanks :) x

**Comment by 2nm** [comment] 2019-01-27 20:45
@m11rphy are you using HomeKit from boot?  If so you might find that you have two config.json flies ?  Honestly removing homebridge from Home App rewriting config.json file and ensuring that all config.json flies are the same fixed all my issues re extra switches.

**Comment by 2nm** [comment] 2019-01-27 21:02
Think I resolved the not turning on.  But do people know about the other issues? X

**Comment by 2nm** [comment] 2019-01-27 21:16
And bizarrely only one TV appears in the remote in control centre

**Comment by creinhart** [comment] 2019-01-27 21:21
I have the same issue of only one TV appearing in Remote in Control center. Perhaps a bug of the first beta?

**Comment by merdok** [comment] 2019-01-27 21:37
@m11rphy read the README, you can disable all other services if you do not wat them

@2nm i do not have 2 TVs so i am not sure what the issue here is, maybe because of the beta?
back and exit buttons work exactly the same as your back and exit buttons on your tv remote control. There is currently no channel changer, maybe Apple will add that in the next betas.

**Comment by seanosullivanuk** [comment] 2019-01-27 21:40
Just a quick one, @merdok. I've set this up from scratch and it's working wonderfully already with my webOS TV. (2018 4k). Thanks for working on this.

**Comment by 2nm** [comment] 2019-01-27 21:48
>@m11rphy read the README, you can disable all other services if you do not wat them ...

@merdok thank you

**Comment by m11rphy** [comment] 2019-01-27 21:55
Hey guys sorry for all the questions, everything was perfect but I now have a error whereby if turn the tv off it shows as off, but 10 seconds later the home app shows the tv as on even tho its not

**Comment by merdok** [comment] 2019-01-27 22:04
@m11rphy Most probably pixel refresher running on your TV (if you have an OLED), during that time (about 9 minutes) the TV appears to be ON (it is actually, just the screen is off). This is an OLED only issue and has nothing to do with this feature.

**Comment by m11rphy** [comment] 2019-01-27 23:08
> @m11rphy Most probably pixel refresher running on your TV (if you have an OLED), during that time (about 9 minutes) the TV appears to be ON (it is actually, just the screen is off). This is an OLED only issue and has nothing to do with this feature.

You was spot on, all back to working as before. Thank you so much for all your work on th plugin and all the help you have given us all. You have done an amazing job and you are a fantastic developer

**Comment by th3cure** [comment] 2019-01-28 00:02
I am having problems with turning the TV on with the home app. Also I can't seem to get renaming the inputs right - have them appear double.
Help appreciated very much!

config:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },

    "description": "David's configuration.",

    "accessories": [
        {
            "accessory": "webostv",
            "name": "LG TV",
            "ip": "xxx.xxx.xxx.xxx",
            "mac": "xx:xx:xx:xx:xx:xx",
            "keyFile": "/Users/davidcox/.homebridge/persist/lgtvKeyFile",
            "pollingInterval": 5,
            "tvService": true,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Nintendo Switch"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Apple TV"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "Xbox One X"
                },
                {
                    "appId": "com.webos.app.hdmi4",
                    "name": "Playstation 4"
                }
            ],
            "volumeControl": false,
            "channelControl": false,
            "mediaControl": false
        }
    ]
}
`

**Comment by th3cure** [comment] 2019-01-28 00:11
I am having problems with turning the TV on with the home app. Also I can't seem to get renaming the inputs right - have them appear double.
Help appreciated very much!

config:
`
"bridge": {
"name": "Homebridge",
"username": "xx:xx:xx:xx:xx:xx",
"port": 51826,
"pin": "xxx-xx-xxx"
},
"description": "My configuration.",
"accessories": [
    {
        "accessory": "webostv",
        "name": "LG TV",
        "ip": "xxx.xxx.xxx.xxx",
        "mac": "xx:xx:xx:xx:xx:xx",
        "keyFile": "/Users/xxxx/.homebridge/persist/lgtvKeyFile",
        "pollingInterval": 5,
        "tvService": true,
        "inputs": [
            {
                "appId": "com.webos.app.hdmi1",
                "name": "Nintendo Switch"
            },
            {
                "appId": "com.webos.app.hdmi2",
                "name": "Apple TV"
            },
            {
                "appId": "com.webos.app.hdmi3",
                "name": "Xbox One X"
            },
            {
                "appId": "com.webos.app.hdmi4",
                "name": "Playstation 4"
            }
        ],
        "volumeControl": false,
        "channelControl": false,
        "mediaControl": false
    }
]
`

**Comment by kapps7** [comment] 2019-01-28 00:16
Can I confirm that those of you who are seeing your TV as the new accessory type TV with integrated inputs etc, are using the unmodified version of this plugin or is there a separate fork ?

**Comment by th3cure** [comment] 2019-01-28 00:17
I am having problems with turning the TV back on with the Home app on iOS.. it seems to disconnect.
Also can I remove any of the pre-configured inputs as AV, Component and Live TV?

**Comment by th3cure** [comment] 2019-01-28 00:17
> Can I confirm that those of you who are seeing your TV as the new accessory type TV (running betas) with integrated inputs etc, are using the unmodified version of this plugin or is there a separate fork ?

just the latest version of this plugin

**Comment by epheterson** [comment] 2019-01-28 01:17
Can we add the ability to override input names, e.g. using "Apple TV" instead of "HDMI1"? Also, as th3cure was asking, can we remove inputs entirely?

**Comment by kapps7** [comment] 2019-01-28 06:11
Is anyone able to change inputs using Siri ?

**Comment by 2nm** [comment] 2019-01-28 14:31
>Can we add the ability to override input names, e.g. using "Apple TV" instead of "HDMI1"? Also, as th3cure was asking, can we remove inputs entirely? ...

@epheterson 

Can just change them in the home app.  Just hit edit and then the TV and then change the input names as you would an accessory input.

**Comment by Hiddecollee** [comment] 2019-01-28 16:31
What features do you think that will be added in the upcoming beta’s?

**Comment by merdok** [comment] 2019-01-28 16:33
Since i do not work at Apple I cannot tell that... We will see in the releases.

**Comment by Hiddecollee** [comment] 2019-01-28 16:34
I thought you could maybe see some things in the API, etc.

**Comment by merdok** [comment] 2019-01-28 16:39
There are references to Picture Mode or Brightness but if and when Apple will implement them i do not know.

**Comment by vmax77** [comment] 2019-01-28 22:17
Fantastic work! Thank you for jumping on this!

**Closed** 2019-01-28 22:18 UTC
Labels: enhancement

**Comment by frizby66** [comment] 2019-01-28 22:22
Hi, having an issue where the module works but I get the message asking me to approve external app popping up for less than a second, every 10 sec or so. Anyone else seeing this?

**Comment by vmax77** [comment] 2019-01-28 22:24
> Hi, having an issue where the module works but I get the message asking me to approve external app popping up for less than a second, every 10 sec or so. Anyone else seeing this?

Hey, is your keyfile (in the config file) location right with write permissions? 

` "keyFile": "/home/pi/.homebridge/lgtvKeyFile"`

**Comment by Hiddecollee** [comment] 2019-01-30 15:53
Hey, everything works great but everytime homebridge is re opent I have to accept the promt.

**Comment by merdok** [comment] 2019-01-30 20:22
@Hiddecollee 
Most probably a permission issue. Make sure that you have write rights to the path for the keyfile.
But this is the wrong issue to report this.

**Comment by nitaybz** [comment] 2019-03-29 13:40
@2nm @creinhart  did you managed to see both TVs in the Control Center?

**Comment by eddydas** [comment] 2020-07-25 05:10
Do you still see the accessory as a non-TV service?
When you tap on the TV tile in Home app, are you unable to see channel lists?
Are you still seeing individual tiles (possibly within the TV tile) representing different sources, but they don't do anything, and you need to use showInputButtons to create yet another set of buttons to switch channels?
Did you have an old version of this plugin from quite some months/years ago?

If the above describes you - you are stuck in the legacy service state. With the latest version (1.9 something) you should see cool awesome TV service with built-in channel lists, like the screenshots at https://www.macstories.net/ios/hands-on-with-ios-12-2s-homekit-support-for-smart-tvs/

The fix is simple!

1. Set hideTvService to true (even when your TV has no native HomeKit support). Restart homebridge.
2. You should now see a dumb accessory representing your TV in your Home app. That's the culprit. Go and remove it using Home app
3. Set hideTvService to false. Restart homebridge.
4. Tap Add accessory, then "Do not have a code". You should now see the TV service available for adding again.

Enjoy!
