### ISSUE TITLE
Not working since 2.0.0 or 2.0.1

### ISSUE THREAD

**Issue by xkyle22x** [merdok/homebridge-webos-tv#289] opened 2020-09-11 01:56 UTC
After update I just have no control of tv in HomeKit. It doesn't recognise state just tells me everything is off. 

I have removed the inputs section completely as you suggested and no difference. 

When I check the logs on homebridge after reboot it tells me tv is ready to control and it recognises that I am using a particular input but then after that point if I change Input or anything else with tv remote the logs don't say anything. 

The device is not no response in home it's just like it is off. 

I have removed plugin and reset homebridge and reboot homehub too. 
Nothing working.

**Comment by merdok** [comment] 2020-09-11 04:23
It would be nice if you could provide a debug log.

**Comment by xkyle22x** [comment] 2020-09-11 04:44
![2E3B5D9F-1E54-4D2F-BC5A-3069344FB0BB](https://user-images.githubusercontent.com/66627364/92861652-1cb49300-f43d-11ea-945a-5eb5ab6bdcb0.png)

Sorry
This was all it gave me and when add the debugging in the config it didn’t give me any more. Was exactly the same.

**Comment by merdok** [comment] 2020-09-11 04:49
This is not the debug log. You need to provide me with the correct debug log. From the standard log above i do not see any issues.

**Comment by Hussamfhaily** [comment] 2020-09-11 19:48
I have the same problem. Nothing works as expected other than changing the channel and that will not happen immediately. In log I get this:
[webostv] [TV] Wake on LAN callback - sent magic packet, trying to connect to tv...

thank you.

**Comment by merdok** [comment] 2020-09-11 20:19
Debug log please, without debug log it is hard to tell at this point what the issue is. Also the tv model would be helpful.

**Comment by realdannys** [comment] 2020-09-12 11:22
Same for me, very patchy performance. I have some buttons remote button sequences programmed and they don't work anymore. Also my TV just disappeared from Home at one point and returned with a different name.

Will try to get a debug log together...

**Comment by realdannys** [comment] 2020-09-12 11:44
Ok things are working again now - not errors from any logs to report.

I seem to have lost the ability to use an active input as a trigger in automation though - is this an intentional change? If so i'll have to go back to v1.

**Comment by merdok** [comment] 2020-09-12 11:56
Not intentional, what tv do you have?

**Comment by realdannys** [comment] 2020-09-12 12:23
It's ok, adding them back as AppID instead of Inputs fixed it. I can now use them again.

**Comment by Hussamfhaily** [comment] 2020-09-12 21:00
[homebridge.log.txt](https://github.com/merdok/homebridge-webos-tv/files/5213238/homebridge.log.txt)

**Comment by merdok** [comment] 2020-09-13 06:22
@Hussamfhaily you have a webos 2.0 tv and there is currently an issue with this webos version. I would recommend for now to downgrade to version 1.9.3 till I find a solution for that.

**Comment by xkyle22x** [comment] 2020-09-13 06:24
I couldn't get homebridge to run in debug for some reason but I had to do the same and downgrade to 1.9.3 and working perfectly again now

**Comment by merdok** [comment] 2020-09-13 07:08
@xkyle22x you most probably also have an webos 2.0 tv which  unfortunately does not have a required services which is used in the new update. You should also for now stay on the 1.9.3 version

**Comment by xkyle22x** [comment] 2020-09-13 08:26
I think my tv is a 2014/2015 model that won't let me turn it on with the plugin if it is off. 
Everything else works but I use a broadlink for the on command. 
I will stay on 1.9.3 for now

**Comment by Hussamfhaily** [comment] 2020-09-13 17:44
> @Hussamfhaily you have a webos 2.0 tv and there is currently an issue with this webos version. I would recommend for now to downgrade to version 1.9.3 till I find a solution for that.

Thank you for what you are doing. I hope you will find a solution in the near future.

**Comment by ggroel** [comment] 2020-09-14 01:32
Sorry for my ignorance, but how downgrade to 1.9.3?

Gastón

**Comment by xkyle22x** [comment] 2020-09-14 05:38
Run in terminal 

npm install -g homebridge-webos-tv@1.9.3

**Comment by ggroel** [comment] 2020-09-14 06:05
Thanks for that!, first uninstall 2.0.1?

Gastón

**Comment by xkyle22x** [comment] 2020-09-14 06:13
Not too sure if your supposed to but I didn't and it was fine

**Comment by agneevX** [comment] 2020-09-14 13:09
I think a separate fork should be created for versions <= 2.0, and development done there, because the new updates are completely unusable for a lot of folks like me. @merdok

**Comment by Salvora** [comment] 2020-09-14 15:50
Just noticed this today. I have the same issue here with LG TV 32LF630V - ZA.

**Comment by alex20081989** [comment] 2020-09-14 16:45
How can I downgrade?
I am using Hoobs and already uninstalled 2.0.1 and tried to install via terminal with npm install -g homebridge-webos-tv@1.9.3 without any errors.

But I can’t see the plug-in in Hoobs.

**Comment by merdok** [comment] 2020-09-14 17:08
@agneevX it will be most probably a separate fork or branch for webos 2.0 users. My goal is to still keep one plugin so I will first try to find a solution to here.
I will create a sticky.

@Salvora yeah, that is I guess also a webos 2.0 tv so please downgrade to 1.9.3

@alex20081989 not sure how to downgrade a plugin in hoobs, maybe some hoobs expert can help?

**Comment by adrianopery** [comment] 2020-09-17 17:15
In my case I have 3 TVs and only one of them is strange.
In the beginning appears many icons on app Home main screen, them I set to join in one icon, so, the TV icon disappear.
On log the tv is active, but I can't see on app home.
The device with issue is TV Sala in **BOLD**
17/09/2020 14:09:32 [webostv] Init - initializing devices
**17/09/2020 14:09:32 [webostv] [TV Sala] Init - got TV configuration, initializing device with name: TV Sala**
17/09/2020 14:09:32 [webostv] [TV quarto master] Init - got TV configuration, initializing device with name: TV quarto master
17/09/2020 14:09:32 [webostv] [TV quarto da frente] Init - got TV configuration, initializing device with name: TV quarto da frente

**Comment by merdok** [comment] 2020-09-18 20:31
@adrianopery you need to provide some more info, what TVs and what is your config.

**Comment by adrianopery** [comment] 2020-09-19 19:36
My tv that is not work is 65UF8500 using firmware 04.06.00.

My setup on hoobs ....
 "mac": "e8-f2-e2-3a-xx-xx”,
        "channelControl": false,
        "notificationButtons": [
            "Movimento detectado na garagem",
            "Portão social foi aberto",
            "Portão da garagem foi aberto",
            "Portão da garagem foi fechado"
        ],
        "volumeControl": "slider",
        "legacyTvService": false,
        "pollingInterval": 5,
        "ip": "192.168.0.xxx”,
        "name": "TV Sala",
        "accessory": "webostv",
        "plugin_map": {
            "index": 0,
            "plugin_name": "homebridge-webos-tv"
        },
        "volumeLimit": 30,
        "infoButtonAction": "INFO",
        "mediaControl": false,
        "prefsDir": "~/.webosTv",
        "inputs": [
            {
                "name": "Home",
                "appId": "com.webos.app.hdmi2"
            },
            {
                "name": "HDMI 1",
                "appId": "com.webos.app.hdmi1"
            },
            {
                "name": "HDMI 3",
                "appId": "com.webos.app.hdmi3"
            },
            {
                "name": " Netflix",
                "appId": "netflix"
            },
            {
                "name": " Amazon",
                "appId": "amazon.global"
            },
            {
                "name": "YouTube",
                "appId": "youtube.leanback.v4"
            }
        ],
        "showInputButtons": false

Thanks

**Comment by merdok** [comment] 2020-09-19 19:58
@adrianopery your TV is a webos 2.0 TV, please wait for a fix. Also your config is not up to date anymore. This has slightly changed in the 2.0.0 update.

**Comment by adrianopery** [comment] 2020-09-19 20:07
Ok I will wait for the fix.
Anyway what is out of date on my setup?
What is your suggestions?

**Comment by merdok** [comment] 2020-09-19 20:40
I hope that i can deliver a fix in the next hours...

Just check the example config in the README and compare to yours, basically some of the points:
- `inputs` has been renamed to `appButtons`
-  `showInputButtons` is removed
-  `infoButtonAction` is removed

**Comment by merdok** [comment] 2020-09-19 21:29
Should be fixed in Version 2.0.3. Can you please confirm?

**Comment by adrianopery** [comment] 2020-09-19 21:32
Sure I can test when you publish.

**Comment by Hussamfhaily** [comment] 2020-09-19 23:28
@merdok thank you. It is working again.

**Comment by xkyle22x** [comment] 2020-09-19 23:51
Merdok so is this a fix for all the webOS 2.0 tv's or something else? 
Should the people waiting on 1.9.3 update to 2.0.3 now?

**Comment by adrianopery** [comment] 2020-09-20 03:19
Hi, sorry for my delay but I just updated and all is working fine!
Greate!
👏🏻👏🏻👏🏻

**Comment by xkyle22x** [comment] 2020-09-20 04:31
Also updated mine too. All working properly now. 
Thanks Merdok

**Comment by merdok** [comment] 2020-09-20 06:48
Yes, all users with webos 2.0 can now safely update to version 2.0.3! I found a solution to include the fix in the main plugin so there is no need for separate plugins😀

**Closed** 2020-09-20 06:48 UTC

**Comment by xkyle22x** [comment] 2020-09-20 06:54
is there a way to not have all the big switches in the HomeKit tile for the media controls but still be able to voice control them with Siri? 
Also now u can't change inputs with Siri anymore?

**Comment by merdok** [comment] 2020-09-20 07:17
Unfortunately there must be a switch in order to be able to control something with Siri. This is a limitation of Homekit.
For inputs you now have the `appButtons` property. Simply add there all your inputs which you want to control with Siri and a switch will appear for each which then can be controlled by Siri.

**Comment by xkyle22x** [comment] 2020-09-20 07:22
Ok thanks. I was hoping there was another way or another option to hide the switches in the config but still control with Siri.
