### ISSUE TITLE
Homekit thinks ON command failed but it didn't

### ISSUE THREAD

**Issue by eisenb11** [merdok/homebridge-webos-tv#80] opened 2018-12-30 21:01 UTC
I'm running into an issue where homekit thinks that the ON command didn't work... but it did. This is happening consistently.

I think homekit is waiting for some kind of response because it says that it's trying, and waiting, then says that it failed.

I've tried the default with polling enabled, tried changing the poll interval to 2, tried disabling polling and the command always works, but it keeps thinking it failed.

This is on a LG 55EF6300 OLED with up-to-date firmware. I believe it uses webos 2.

**Comment by merdok** [comment] 2018-12-30 21:43
How about the device where you run Homebridge on, maybe it is overloaded? What device are you running Homebridge on?
Also I would suggest to first try just with a fresh install and just this plugin installed, then at least we will know if the plugin is the cause.

**Comment by eisenb11** [comment] 2018-12-30 22:00
It’s on a Raspberry Pi, but it’s doing nothing else right now. This is a new set up that I got running yesterday.

 

It seems that the device status is showing up correctly, but for whatever reason Siri still seems to think that the device didn’t turn on.

 

I probably should have specified that the issue is with using Siri (as opposed to the home app).

**Comment by merdok** [comment] 2018-12-30 22:38
There was already a similar issue with Siri before which should be fixed by now.  Are you using the latest version?
See here: #50

**Comment by eisenb11** [comment] 2018-12-30 22:42
Interesting. I’m using the version that came down when I did “sudo npm install -g homebridge-webos-tv” this afternoon. Is that the latest, or should I grab the files from github?

**Comment by eisenb11** [comment] 2018-12-31 07:52
I just compared my index.js file with the one on github with beyond compare... and they appear to be the same. The issue in #50 appears to be similar to what I'm experiencing with the current version. Is there more info that I can provide to help? Thanks.

**Comment by merdok** [comment] 2018-12-31 08:51
I would guess that this is most probably an issue which has something to do with your environment. Could be your network or could be your raspberry pi. 
You should try to do some testing to narrow the issue down. Do you have other homebridge plugins installed?

**Comment by eisenb11** [comment] 2018-12-31 09:38
I have added more plugins since then and all of them are working correctly. The pi is running a new image that I set up last night. It's terminal only (no GUI windows manager) so it's under negligible load.  Network is 1gb and mostly wired.

**Comment by merdok** [comment] 2018-12-31 17:46
Please remove all other plugins and check if the issue still exists. Also your TV is connected through WiFi or LAN? You might want to switch that too and see if that fixes the issue.

**Comment by eisenb11** [comment] 2018-12-31 18:39
I removed all of the other accessories and the problem still persists. TV turns on and off, but Siri thinks it didn't turn on. OFF command works without issue, it's only the ON command. The TV is on the wired network which is very speedy - not sure how fast, but last least 70 MB/s sustained during SMB file transfers over the 1 Gb/s link.

**Comment by merdok** [comment] 2019-01-01 16:31
Unfortunately i cannot reproduce this issue with my setup. I also do not have any other idea what it could be. You could switch to WiFi to be sure that your wired network is not the issue. Your webos2 TV might also be the issue, but i cannot be certain about that since i do not have access to such TV. 
Could you describe more detailed when the issue is occurring? So you cannot turn on your TV using Siri?

**Comment by eisenb11** [comment] 2019-01-01 17:31
Thanks for the help, and happy new year. Here's a rough transcript of what happens:

Me: Hey Siri, turn on TV power
Siri: OK...
TV: Turns on
... some time passes ...
Siri: I'm still working on it
... some time passes ...
Siri: Some devices are not responding

The command works and the TV turns on, but for some reason Siri thinks it didn't.

**Comment by merdok** [comment] 2019-01-02 15:00
Oh, then maybe just your webos2 TV takes so long to start up (till it is visible on the network). You could try to start the TV and then do manual ping to your TV from your PC and see how long it takes till a response is finally coming to confirm that this is the issue.

**Comment by eisenb11** [comment] 2019-01-03 16:51
I did the ping test that you suggested. It took approx 6-7 seconds between the TV turning on and it responding to the ping requests.

**Comment by merdok** [comment] 2019-01-03 18:54
And this will probably be the issue. I guess that Siri responds with "Some devices are not responding" when it takes too long. If you can, please try to modify the code, line 460 and 480, and set the value there to something lower like 3000 and let me know if that fixes the issue.

**Comment by danbridgland** [comment] 2019-01-03 22:20
I’m seeing the same issue.  Latest WebOS, RaspberryPi, latest Homebridge, latest version of Homebridge-WebOS-TV, all new image as of yesterday, all other HomeKit accessories working fine.  Even other attributes of the Homebridge-WebOS-TV package working fine.  Only problem is with the power.

**Comment by eisenb11** [comment] 2019-01-04 04:11
I reduced the timeout from 5000 to 3000 at the 2 locations but it didn't fix the issue. I also tried 1000 and increased the wake loop from 3 to 15 times to compensate for the shorter duration with the same result.

**Comment by merdok** [comment] 2019-01-04 10:48
@danbridgland do you also have a webos2 TV?

**Comment by danbridgland** [comment] 2019-01-04 13:07
I believe so, LG OLED55B7V

**Comment by merdok** [comment] 2019-01-04 19:06
@danbridgland well that is a webos3.5 TV... This makes this pretty complicated.

**Comment by danbridgland** [comment] 2019-01-04 22:50
The OLED55B7V is a highly popular TV, likely to have other people hitting this issue too.  Any ideas for fault finding this?

**Comment by eisenb11** [comment] 2019-01-05 17:15
I do think I have the fast power on option.

**Comment by merdok** [comment] 2019-01-05 17:37
Quick start i mean.

**Comment by danbridgland** [comment] 2019-01-05 18:07
I have Quick Start+ set to enabled.

**Comment by merdok** [comment] 2019-01-05 20:59
Ok, well i might have an idea how to fix this, but unfortunately after doing and npm update i broke my homebridge and my devices are not available anymore for some reason... I have to first fix this.

**Comment by merdok** [comment] 2019-01-06 16:10
@eisenb11 @danbridgland 
Could you please update to version 1.2.0 and test if your issues are solved?

**Comment by eisenb11** [comment] 2019-01-06 18:42
I just did a npm install to get the updated version and confirmed that the file size of index.js had changed. Ran a test and the issue has been resolved! Thanks very much for looking into this for us!

**Comment by merdok** [comment] 2019-01-06 18:47
Good to hear 👍  Glad i could help!

**Closed by merdok** 2019-01-06 18:47 UTC

**Comment by danbridgland** [comment] 2019-01-06 20:10
Works for me too.  Thank you @Merdok.

However...
When switching on the TV, the state of the Home app icon for the TV changes briefly from off to on, then back to off, all within 2 seconds, the TV takes a further second or two to turn on, after which point and another second or two, the icon on the Home app changes back to on.   
Using the home app to turn the TV off works fine.

Using Siri to turn the TV on works fine, but turning the TV off, I get an error response, “The TV is not responding”.

Perhaps a delay in reading the state awareness could be helpful?

However, that said, I’m very greatful for your assistance in getting to this point. Thank you again @Merdok.

**Comment by merdok** [comment] 2019-01-06 20:50
This has to be like that. Before the plugin blocked homebridge till the TV responded. Now the plugin is not waiting for the TV to turn on, instead as soon as the TV turns on the correct status will be send to homebridge. When you increase the polling interval then this will not occur that much.

The TV is ON for homebridge when it is available on the network, this might take a while even when the picture is already available on the TV. This is something i cannot change. If you turn on and off the tv within seconds then you will still get the not responding error, because the connection was not yet established.

**Comment by merdok** [comment] 2019-01-06 21:36
Unfortunately that is not possible.

**Comment by danbridgland** [comment] 2019-01-06 21:40
That is a shame.  Great work on the fix,  I will have to rely on ARC/CEC to turn off the TV.

**Comment by merdok** [comment] 2019-01-06 23:01
@danbridgland could you try the update which i just pushed (1.2.1), this should fix your issues with turning off the TV.

**Comment by merdok** [comment] 2019-01-06 23:35
Good to hear that this is also fixed now 👍 
I do not have a Patreon, just PayPal donations.

**Comment by danbridgland** [comment] 2019-01-07 00:03
DM me your PayPal details via twitter, I’ll make a small contribution.

Thanks again.
Dan
