### ISSUE TITLE
Problem with Homebridge 1.3.5

### ISSUE THREAD

**Issue by ThomasMeyer1970** [merdok/homebridge-webos-tv#405] opened 2021-11-07 14:52 UTC
Hello,

thank you for your great job!
There is a big problem with the home bridge version 1.3.5 - mkdir failed - Homebridge restarts

Please take a look 

thank you and best regards
Thomas

**Comment by merdok** [comment] 2021-11-07 15:32
There are no issues with homebridge 1.3.5 and mkdir! All is working fine! I think your issue is related to your environment...

**Comment by ThomasMeyer1970** [comment] 2021-11-08 14:29
The plugin stopped working with the 1.3.5 Upgrade!
Error: EACCES: permission denied, mkdir '/root/.lgtv2'

**Comment by merdok** [comment] 2021-11-08 15:05
This is an issue with your file system and not homebridge or the plugin. Homebridge cannot read the file on the specified directory, you need to fix your permission. Maybe you did the homebridge update as a root where previously it was with your user and that might have broken the permissions.

**Comment by raspberrycoulis** [comment] 2021-11-17 11:49
I found this after experiencing the same issue as @ThomasMeyer1970.

I've been using Homebridge for some time now, and my upgrade process has always been the same. I'm running the Docker container, so I basically use Portainer to recreate the container whilst pulling the latest image - has worked flawlessly for ages. Prior to using Portainer, I followed the upgrade steps on your wiki, which is basically what Portainer does but via a GUI.

Nothing has changed in the setup, but there is now an error as @ThomasMeyer1970 has highlighted. So do you have any suggestions as to what to do here @merdok, because right now my Homebridge won't start because of the issue above so I have to disable the plugin to get everything working and is not ideal?

**Comment by merdok** [comment] 2021-11-17 12:22
I want to highlight again that the issue is not related to this plugin but to your homebridge installation. 
For some reason for you guys the homebridge home directory changed to /root/ probably because you installed homebridge as root user. On the other hand you do not run your homebridge instance with the root user but probably with a normal user hence it is not possible to for homebridge to write the config in that directory.

I see two solutions here for you:
1. Fix your homebridge installation so that it is installed and run with the correct user.
2. You can specify in the config.json a custom folder where the plugin should write the preferences. Just check "prefsDir" in the README and specify a path where the user which you are using to start homebridge has write permissions.

**Comment by raspberrycoulis** [comment] 2021-11-17 12:39
Ok, what's with the tone of the replies? We're genuinely trying to be helpful here, but all myself and @ThomasMeyer1970 have received back are snarky replies that just fobs us off. Apologies if we came across any other way, but our installation went from working perfectly to not, and as you are the creator or the plugin that seems to be affected, we've created an issue here with detail that should hopefully help...

I'm running Homebridge in Docker on a Synology NAS (not running DSM 7 yet) and have followed their instructions as to how to install and run Homebridge. This has been working just fine for a few years, but maybe their recent update broke something here. 

I also run Homebridge natively on a Raspberry Pi 4, and I tested your plugin there and it seems to work without the error - so it does look more likely that it is down to the Homebridge Docker container now, but this has only really come about because I've tried to help you by providing feedback and useful information, as opposed to just saying "it's not me, it's you".

I don't want to risk wrecking my Homebridge setup by messing around with user permissions, so I tried your second recommendation:

>You can specify in the config.json a custom folder where the plugin should write the preferences. Just check "prefsDir" in the README and specify a path where the user which you are using to start homebridge has write permissions.

That didn't work either - I created two new folders within the Homebridge folder `lg-webos-tv-prefs` and `lg-webos-tv-keyfiles` and set the paths accordingly in the plugin settings, restarted Homebridge but the same error comes up about `/root/.lgtv2`.

I guess we'll have to take this to [https://github.com/oznu/docker-homebridge](https://github.com/oznu/docker-homebridge).

**Comment by oznu** [comment] 2021-11-17 12:51
Plugins should only write to the homebridge storage directory; not the "user" directory.

https://github.com/homebridge/verified#requirements

> If the plugin needs to write files to disk (cache, keys, etc.), it must store them inside the Homebridge storage directory.

**Comment by raspberrycoulis** [comment] 2021-11-17 12:58
https://github.com/oznu/docker-homebridge/issues/397#issuecomment-971551471

**Comment by merdok** [comment] 2021-11-17 13:23
@oznu the plugin is writing to the homebridge path "api.user.storagePath()", or is that wrong?

@raspberrycoulis you need to understand that you have some kind of issue with your setup. I cannot repeat myself each time with the same answer over and over again. Since I do not have access to your particular setup I cannot tell you exactly what the issue is on your side, every setup is different and there are many stuff which might affect it which are out my control. I gave you two passionless solutions which based on your information might help you.

**Comment by oznu** [comment] 2021-11-17 13:38
> @oznu the plugin is writing to the homebridge storage directory "api.user.storagePath()", or is that wrong?

That is correct. I would double check to confirm it's working as expected and the value is being passed through to the third party library.

When using the Docker image the Homebridge storage directory is `/homebridge` (this is the persistent volume for the Docker container).

**Comment by merdok** [comment] 2021-11-17 14:22
@oznu the question is now, why suddenly after the update to 1.3.5 they are getting the wrong storage path with the exact same code. As they say, before the update everything was fine.

@raspberrycoulis and @ThomasMeyer1970 can you please post your config.json entries for the tv to make sure you have nothing wrong entered there?

**Comment by raspberrycoulis** [comment] 2021-11-17 14:37
> @oznu the question is now, why suddenly after the update to 1.3.5 they are getting the wrong storage path with the exact same code. As they say, before the update everything was fine.

This is exactly my question too. Plugin worked perfectly until I updated Homebridge today (which uses the `:latest` tag from Docker, which I understand was updated on 15 November).

Here's the relevant parts of my config with certain elements redacted for security reasons:

```json
        {
            "devices": [
                {
                    "name": "LG TV",
                    "ip": "192.168.1.20",
                    "mac": "XX:XX:XX:XX:XX:XX",
                    "pollingInterval": 10,
                    "volumeLimit": 100,
                    "volumeControl": "both",
                    "channelControl": true,
                    "mediaControl": false
                }
            ],
            "platform": "webostv"
        },
```

I've ran my entire `config.json` through [JSONLint](https://jsonlint.com/) and it is valid.

**Comment by ThomasMeyer1970** [comment] 2021-11-17 14:56
Plugin worked perfectly until I updated Homebridge to version 1.3.5  around 10 days ago. 

Here is the part of my config:

       {
            "devices": [
                {
                    "name": "LG TV",
                    "ip": "192.168.178.53",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "hideTvService": true,
                    "volumeLimit": 100,
                    "volumeControl": "both",
                    "channelControl": true,
                    "appButtons": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "LIVE TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "HDMI Input"
                        },
                        {
                            "appId": "com.webos.app.igallery",
                            "name": "Gallery"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        }
    ],
    "disabledPlugins": [
        "homebridge-webos-tv"
    ]
}

**Comment by merdok** [comment] 2021-11-17 16:47
config.json looks perfectly fine for both of you. The thing you can try is to add the `keyFile` property and specify a path to a file in a directory where you have write permissions.

**Comment by dennypage** [comment] 2021-11-17 17:02
Beating up the developer plugin isn't productive. Look at the code.

Yes, it's coming from the mkdir on the line you referenced. If you look at the persist-path [here](https://github.com/hobbyquaker/persist-path/blob/master/index.js), you will see that the path is constructed by taking the value of HOME and appending '.' and 'lgtv2' to it. Your HOME variable is defaulting to '/root/'.

Somewhere along the line, lgtv2 is expecting HOME to be properly set.

**Comment by raspberrycoulis** [comment] 2021-11-17 17:06
Is there a way to override the HOME path manually? Looking at the `lgtv2` repo, it hasn't been touched for some time, so it seems unlikely that anything will be changed there. However, why would it work just fine for ages, only to break after the Homebridge Docker image was updated 2 days ago?

**Comment by merdok** [comment] 2021-11-17 18:09
The line 48 here https://github.com/hobbyquaker/lgtv2/blob/master/index.js#L48 is certainly not perfect, since even when you specify the `keyFile` this directory is tried to be created which for you fails, that is why specifying the `keyFile` brings nothing.
Anyway, since you say that it was running before the update that means that the line above, although not ideal, is not the main issue here.
My suspicions is that something changed with the setup how you run homebridge after your recent update. I cannot tell how or what exactly, but somehow your home directory (HOME env variable) is set to `/root/` to which homerbidge does not have permissions to write because you probably do not run it with the root user. Maybe you run the update with the root user where before you did it with your normal user? Any plugin which will try to write to your home directory will now always fails since it will always point to` /root/`

**Comment by raspberrycoulis** [comment] 2021-11-17 18:15
Bizarre. Absolutely nothing has changed in my setup. Nothing. I have updated the Docker container the same way I have always done it and it's worked just fine.

I've got Homebridge running on a Raspberry Pi (non-Dockerised) and the plug-in works fine there so I'll stick with that.

**Comment by dennypage** [comment] 2021-11-17 18:27
> Is there a way to override the HOME path manually?

Perhaps set a HOME environment value in the container?

**Comment by raspberrycoulis** [comment] 2021-11-17 18:31
> > Is there a way to override the HOME path manually?
> 
> 
> 
> Perhaps set a HOME environment value in the container?

Any ideas on how to do that?

**Comment by merdok** [comment] 2021-11-17 18:36
Yeah, well i cannot tell what changed but definitely something changed...
I have summited a pull request to the lgtv2 repo to fix the unnecessary creation of the directory when the `keyFile` is specified, but from experience it might take some time till gets reviewed and merged...

**Comment by dennypage** [comment] 2021-11-17 18:39
> Any ideas on how to do that?

You indicated that you were using Synology...

Same way you did when you initially installed the container. Open the Docker tool on your Synology. Select the container in question, shut it down (if running) and then click Edit. Select Environment and add variable called HOME with an appropriate value. Something that is valid within the container like "/homebridge/home/"

**Comment by ThomasMeyer1970** [comment] 2021-11-25 14:26
I have just set up my entire homebridge docker instance from scratch. Everything including plugins works perfectly - with the exception of the WEBOS TV plugin! Same error as before - so it's definitely a code problem ...

**Comment by merdok** [comment] 2021-11-25 14:44
It has been already cleared that the issue has nothing to do with the latest homebridge update or with this plugin.
You have the issue because something in your system related to the user changed and the HOME environment variable points to a non writable directory. Nothing in that code changed in the past few years.
The dependency which causes the issue indeed is handling the creation of that directory not optimal since it is not necessary to create it and I have already submitted a pull request to fix that, but like already mentioned that code did not change since a very long time. So something in your system has changed which is now causing the issue, until my pull request is not merged you will have to figure out what caused the issue in your system to fix it.

**Closed by merdok** 2021-11-25 14:44 UTC

**Comment by allai** [comment] 2021-11-25 20:39
> I have just set up my entire homebridge docker instance from scratch. Everything including plugins works perfectly - with the exception of the WEBOS TV plugin! Same error as before - so it's definitely a code problem ...

Hey, just wanted to chime in because I've been experiencing this annoying issue for the last week with a nearly identical setup: a Synology DS718+ running the latest homebridge-docker being managed by portainer. I tried @dennypage's suggestion and everything is finally fixed. Add a HOME variable to /homebridge/home and maybe you won't have to wait for that request to get merged.

**Comment by Xusqui** [comment] 2021-12-29 14:06
oops... Trying this completely broke my instance... Only get this error over and over in the logs:

s6-applyuidgid: fatal: unable to exec tail: Permission denied                                                                                                                                          
s6-applyuidgid: fatal: unable to exec tail: Permission denied                                                                                                                                          
s6-applyuidgid: fatal: unable to exec tail: Permission denied                                                                                                                                          
s6-applyuidgid: fatal: unable to exec tail: Permission denied                                                                                                                                          
s6-applyuidgid: fatal: unable to exec tail: Permission denied
